// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newAnalysisReport(db *gorm.DB, opts ...gen.DOOption) analysisReport {
	_analysisReport := analysisReport{}

	_analysisReport.analysisReportDo.UseDB(db, opts...)
	_analysisReport.analysisReportDo.UseModel(&entity.AnalysisReport{})

	tableName := _analysisReport.analysisReportDo.TableName()
	_analysisReport.ALL = field.NewAsterisk(tableName)
	_analysisReport.ID = field.NewInt64(tableName, "id")
	_analysisReport.VariantID = field.NewInt64(tableName, "variant_id")
	_analysisReport.OverallScore = field.NewInt32(tableName, "overall_score")
	_analysisReport.ReportData = field.NewField(tableName, "report_data")
	_analysisReport.AnalyzedAt = field.NewTime(tableName, "analyzed_at")
	_analysisReport.CreatedAt = field.NewTime(tableName, "created_at")

	_analysisReport.fillFieldMap()

	return _analysisReport
}

type analysisReport struct {
	analysisReportDo analysisReportDo

	ALL          field.Asterisk
	ID           field.Int64
	VariantID    field.Int64
	OverallScore field.Int32
	ReportData   field.Field
	AnalyzedAt   field.Time
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (a analysisReport) Table(newTableName string) *analysisReport {
	a.analysisReportDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a analysisReport) As(alias string) *analysisReport {
	a.analysisReportDo.DO = *(a.analysisReportDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *analysisReport) updateTableName(table string) *analysisReport {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.VariantID = field.NewInt64(table, "variant_id")
	a.OverallScore = field.NewInt32(table, "overall_score")
	a.ReportData = field.NewField(table, "report_data")
	a.AnalyzedAt = field.NewTime(table, "analyzed_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *analysisReport) WithContext(ctx context.Context) IAnalysisReportDo {
	return a.analysisReportDo.WithContext(ctx)
}

func (a analysisReport) TableName() string { return a.analysisReportDo.TableName() }

func (a analysisReport) Alias() string { return a.analysisReportDo.Alias() }

func (a analysisReport) Columns(cols ...field.Expr) gen.Columns {
	return a.analysisReportDo.Columns(cols...)
}

func (a *analysisReport) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *analysisReport) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["variant_id"] = a.VariantID
	a.fieldMap["overall_score"] = a.OverallScore
	a.fieldMap["report_data"] = a.ReportData
	a.fieldMap["analyzed_at"] = a.AnalyzedAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a analysisReport) clone(db *gorm.DB) analysisReport {
	a.analysisReportDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a analysisReport) replaceDB(db *gorm.DB) analysisReport {
	a.analysisReportDo.ReplaceDB(db)
	return a
}

type analysisReportDo struct{ gen.DO }

type IAnalysisReportDo interface {
	gen.SubQuery
	Debug() IAnalysisReportDo
	WithContext(ctx context.Context) IAnalysisReportDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAnalysisReportDo
	WriteDB() IAnalysisReportDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAnalysisReportDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAnalysisReportDo
	Not(conds ...gen.Condition) IAnalysisReportDo
	Or(conds ...gen.Condition) IAnalysisReportDo
	Select(conds ...field.Expr) IAnalysisReportDo
	Where(conds ...gen.Condition) IAnalysisReportDo
	Order(conds ...field.Expr) IAnalysisReportDo
	Distinct(cols ...field.Expr) IAnalysisReportDo
	Omit(cols ...field.Expr) IAnalysisReportDo
	Join(table schema.Tabler, on ...field.Expr) IAnalysisReportDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAnalysisReportDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAnalysisReportDo
	Group(cols ...field.Expr) IAnalysisReportDo
	Having(conds ...gen.Condition) IAnalysisReportDo
	Limit(limit int) IAnalysisReportDo
	Offset(offset int) IAnalysisReportDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAnalysisReportDo
	Unscoped() IAnalysisReportDo
	Create(values ...*entity.AnalysisReport) error
	CreateInBatches(values []*entity.AnalysisReport, batchSize int) error
	Save(values ...*entity.AnalysisReport) error
	First() (*entity.AnalysisReport, error)
	Take() (*entity.AnalysisReport, error)
	Last() (*entity.AnalysisReport, error)
	Find() ([]*entity.AnalysisReport, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AnalysisReport, err error)
	FindInBatches(result *[]*entity.AnalysisReport, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AnalysisReport) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAnalysisReportDo
	Assign(attrs ...field.AssignExpr) IAnalysisReportDo
	Joins(fields ...field.RelationField) IAnalysisReportDo
	Preload(fields ...field.RelationField) IAnalysisReportDo
	FirstOrInit() (*entity.AnalysisReport, error)
	FirstOrCreate() (*entity.AnalysisReport, error)
	FindByPage(offset int, limit int) (result []*entity.AnalysisReport, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAnalysisReportDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a analysisReportDo) Debug() IAnalysisReportDo {
	return a.withDO(a.DO.Debug())
}

func (a analysisReportDo) WithContext(ctx context.Context) IAnalysisReportDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a analysisReportDo) ReadDB() IAnalysisReportDo {
	return a.Clauses(dbresolver.Read)
}

func (a analysisReportDo) WriteDB() IAnalysisReportDo {
	return a.Clauses(dbresolver.Write)
}

func (a analysisReportDo) Session(config *gorm.Session) IAnalysisReportDo {
	return a.withDO(a.DO.Session(config))
}

func (a analysisReportDo) Clauses(conds ...clause.Expression) IAnalysisReportDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a analysisReportDo) Returning(value interface{}, columns ...string) IAnalysisReportDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a analysisReportDo) Not(conds ...gen.Condition) IAnalysisReportDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a analysisReportDo) Or(conds ...gen.Condition) IAnalysisReportDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a analysisReportDo) Select(conds ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a analysisReportDo) Where(conds ...gen.Condition) IAnalysisReportDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a analysisReportDo) Order(conds ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a analysisReportDo) Distinct(cols ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a analysisReportDo) Omit(cols ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a analysisReportDo) Join(table schema.Tabler, on ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a analysisReportDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a analysisReportDo) RightJoin(table schema.Tabler, on ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a analysisReportDo) Group(cols ...field.Expr) IAnalysisReportDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a analysisReportDo) Having(conds ...gen.Condition) IAnalysisReportDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a analysisReportDo) Limit(limit int) IAnalysisReportDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a analysisReportDo) Offset(offset int) IAnalysisReportDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a analysisReportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAnalysisReportDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a analysisReportDo) Unscoped() IAnalysisReportDo {
	return a.withDO(a.DO.Unscoped())
}

func (a analysisReportDo) Create(values ...*entity.AnalysisReport) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a analysisReportDo) CreateInBatches(values []*entity.AnalysisReport, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a analysisReportDo) Save(values ...*entity.AnalysisReport) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a analysisReportDo) First() (*entity.AnalysisReport, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AnalysisReport), nil
	}
}

func (a analysisReportDo) Take() (*entity.AnalysisReport, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AnalysisReport), nil
	}
}

func (a analysisReportDo) Last() (*entity.AnalysisReport, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AnalysisReport), nil
	}
}

func (a analysisReportDo) Find() ([]*entity.AnalysisReport, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AnalysisReport), err
}

func (a analysisReportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AnalysisReport, err error) {
	buf := make([]*entity.AnalysisReport, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a analysisReportDo) FindInBatches(result *[]*entity.AnalysisReport, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a analysisReportDo) Attrs(attrs ...field.AssignExpr) IAnalysisReportDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a analysisReportDo) Assign(attrs ...field.AssignExpr) IAnalysisReportDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a analysisReportDo) Joins(fields ...field.RelationField) IAnalysisReportDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a analysisReportDo) Preload(fields ...field.RelationField) IAnalysisReportDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a analysisReportDo) FirstOrInit() (*entity.AnalysisReport, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AnalysisReport), nil
	}
}

func (a analysisReportDo) FirstOrCreate() (*entity.AnalysisReport, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AnalysisReport), nil
	}
}

func (a analysisReportDo) FindByPage(offset int, limit int) (result []*entity.AnalysisReport, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a analysisReportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a analysisReportDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a analysisReportDo) Delete(models ...*entity.AnalysisReport) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *analysisReportDo) withDO(do gen.Dao) *analysisReportDo {
	a.DO = *do.(*gen.DO)
	return a
}
