// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newDesignGuideLike(db *gorm.DB, opts ...gen.DOOption) designGuideLike {
	_designGuideLike := designGuideLike{}

	_designGuideLike.designGuideLikeDo.UseDB(db, opts...)
	_designGuideLike.designGuideLikeDo.UseModel(&entity.DesignGuideLike{})

	tableName := _designGuideLike.designGuideLikeDo.TableName()
	_designGuideLike.ALL = field.NewAsterisk(tableName)
	_designGuideLike.ID = field.NewInt64(tableName, "id")
	_designGuideLike.DesignGuideID = field.NewInt64(tableName, "design_guide_id")
	_designGuideLike.UserID = field.NewInt64(tableName, "user_id")
	_designGuideLike.CreatedAt = field.NewTime(tableName, "created_at")

	_designGuideLike.fillFieldMap()

	return _designGuideLike
}

type designGuideLike struct {
	designGuideLikeDo designGuideLikeDo

	ALL           field.Asterisk
	ID            field.Int64
	DesignGuideID field.Int64
	UserID        field.Int64
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (d designGuideLike) Table(newTableName string) *designGuideLike {
	d.designGuideLikeDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d designGuideLike) As(alias string) *designGuideLike {
	d.designGuideLikeDo.DO = *(d.designGuideLikeDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *designGuideLike) updateTableName(table string) *designGuideLike {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DesignGuideID = field.NewInt64(table, "design_guide_id")
	d.UserID = field.NewInt64(table, "user_id")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *designGuideLike) WithContext(ctx context.Context) IDesignGuideLikeDo {
	return d.designGuideLikeDo.WithContext(ctx)
}

func (d designGuideLike) TableName() string { return d.designGuideLikeDo.TableName() }

func (d designGuideLike) Alias() string { return d.designGuideLikeDo.Alias() }

func (d designGuideLike) Columns(cols ...field.Expr) gen.Columns {
	return d.designGuideLikeDo.Columns(cols...)
}

func (d *designGuideLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *designGuideLike) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 4)
	d.fieldMap["id"] = d.ID
	d.fieldMap["design_guide_id"] = d.DesignGuideID
	d.fieldMap["user_id"] = d.UserID
	d.fieldMap["created_at"] = d.CreatedAt
}

func (d designGuideLike) clone(db *gorm.DB) designGuideLike {
	d.designGuideLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d designGuideLike) replaceDB(db *gorm.DB) designGuideLike {
	d.designGuideLikeDo.ReplaceDB(db)
	return d
}

type designGuideLikeDo struct{ gen.DO }

type IDesignGuideLikeDo interface {
	gen.SubQuery
	Debug() IDesignGuideLikeDo
	WithContext(ctx context.Context) IDesignGuideLikeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDesignGuideLikeDo
	WriteDB() IDesignGuideLikeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDesignGuideLikeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDesignGuideLikeDo
	Not(conds ...gen.Condition) IDesignGuideLikeDo
	Or(conds ...gen.Condition) IDesignGuideLikeDo
	Select(conds ...field.Expr) IDesignGuideLikeDo
	Where(conds ...gen.Condition) IDesignGuideLikeDo
	Order(conds ...field.Expr) IDesignGuideLikeDo
	Distinct(cols ...field.Expr) IDesignGuideLikeDo
	Omit(cols ...field.Expr) IDesignGuideLikeDo
	Join(table schema.Tabler, on ...field.Expr) IDesignGuideLikeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDesignGuideLikeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDesignGuideLikeDo
	Group(cols ...field.Expr) IDesignGuideLikeDo
	Having(conds ...gen.Condition) IDesignGuideLikeDo
	Limit(limit int) IDesignGuideLikeDo
	Offset(offset int) IDesignGuideLikeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDesignGuideLikeDo
	Unscoped() IDesignGuideLikeDo
	Create(values ...*entity.DesignGuideLike) error
	CreateInBatches(values []*entity.DesignGuideLike, batchSize int) error
	Save(values ...*entity.DesignGuideLike) error
	First() (*entity.DesignGuideLike, error)
	Take() (*entity.DesignGuideLike, error)
	Last() (*entity.DesignGuideLike, error)
	Find() ([]*entity.DesignGuideLike, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.DesignGuideLike, err error)
	FindInBatches(result *[]*entity.DesignGuideLike, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.DesignGuideLike) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDesignGuideLikeDo
	Assign(attrs ...field.AssignExpr) IDesignGuideLikeDo
	Joins(fields ...field.RelationField) IDesignGuideLikeDo
	Preload(fields ...field.RelationField) IDesignGuideLikeDo
	FirstOrInit() (*entity.DesignGuideLike, error)
	FirstOrCreate() (*entity.DesignGuideLike, error)
	FindByPage(offset int, limit int) (result []*entity.DesignGuideLike, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDesignGuideLikeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d designGuideLikeDo) Debug() IDesignGuideLikeDo {
	return d.withDO(d.DO.Debug())
}

func (d designGuideLikeDo) WithContext(ctx context.Context) IDesignGuideLikeDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d designGuideLikeDo) ReadDB() IDesignGuideLikeDo {
	return d.Clauses(dbresolver.Read)
}

func (d designGuideLikeDo) WriteDB() IDesignGuideLikeDo {
	return d.Clauses(dbresolver.Write)
}

func (d designGuideLikeDo) Session(config *gorm.Session) IDesignGuideLikeDo {
	return d.withDO(d.DO.Session(config))
}

func (d designGuideLikeDo) Clauses(conds ...clause.Expression) IDesignGuideLikeDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d designGuideLikeDo) Returning(value interface{}, columns ...string) IDesignGuideLikeDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d designGuideLikeDo) Not(conds ...gen.Condition) IDesignGuideLikeDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d designGuideLikeDo) Or(conds ...gen.Condition) IDesignGuideLikeDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d designGuideLikeDo) Select(conds ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d designGuideLikeDo) Where(conds ...gen.Condition) IDesignGuideLikeDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d designGuideLikeDo) Order(conds ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d designGuideLikeDo) Distinct(cols ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d designGuideLikeDo) Omit(cols ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d designGuideLikeDo) Join(table schema.Tabler, on ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d designGuideLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d designGuideLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d designGuideLikeDo) Group(cols ...field.Expr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d designGuideLikeDo) Having(conds ...gen.Condition) IDesignGuideLikeDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d designGuideLikeDo) Limit(limit int) IDesignGuideLikeDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d designGuideLikeDo) Offset(offset int) IDesignGuideLikeDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d designGuideLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDesignGuideLikeDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d designGuideLikeDo) Unscoped() IDesignGuideLikeDo {
	return d.withDO(d.DO.Unscoped())
}

func (d designGuideLikeDo) Create(values ...*entity.DesignGuideLike) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d designGuideLikeDo) CreateInBatches(values []*entity.DesignGuideLike, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d designGuideLikeDo) Save(values ...*entity.DesignGuideLike) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d designGuideLikeDo) First() (*entity.DesignGuideLike, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuideLike), nil
	}
}

func (d designGuideLikeDo) Take() (*entity.DesignGuideLike, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuideLike), nil
	}
}

func (d designGuideLikeDo) Last() (*entity.DesignGuideLike, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuideLike), nil
	}
}

func (d designGuideLikeDo) Find() ([]*entity.DesignGuideLike, error) {
	result, err := d.DO.Find()
	return result.([]*entity.DesignGuideLike), err
}

func (d designGuideLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.DesignGuideLike, err error) {
	buf := make([]*entity.DesignGuideLike, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d designGuideLikeDo) FindInBatches(result *[]*entity.DesignGuideLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d designGuideLikeDo) Attrs(attrs ...field.AssignExpr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d designGuideLikeDo) Assign(attrs ...field.AssignExpr) IDesignGuideLikeDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d designGuideLikeDo) Joins(fields ...field.RelationField) IDesignGuideLikeDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d designGuideLikeDo) Preload(fields ...field.RelationField) IDesignGuideLikeDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d designGuideLikeDo) FirstOrInit() (*entity.DesignGuideLike, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuideLike), nil
	}
}

func (d designGuideLikeDo) FirstOrCreate() (*entity.DesignGuideLike, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuideLike), nil
	}
}

func (d designGuideLikeDo) FindByPage(offset int, limit int) (result []*entity.DesignGuideLike, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d designGuideLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d designGuideLikeDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d designGuideLikeDo) Delete(models ...*entity.DesignGuideLike) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *designGuideLikeDo) withDO(do gen.Dao) *designGuideLikeDo {
	d.DO = *do.(*gen.DO)
	return d
}
