// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newDesignGuide(db *gorm.DB, opts ...gen.DOOption) designGuide {
	_designGuide := designGuide{}

	_designGuide.designGuideDo.UseDB(db, opts...)
	_designGuide.designGuideDo.UseModel(&entity.DesignGuide{})

	tableName := _designGuide.designGuideDo.TableName()
	_designGuide.ALL = field.NewAsterisk(tableName)
	_designGuide.ID = field.NewInt64(tableName, "id")
	_designGuide.Name = field.NewString(tableName, "name")
	_designGuide.Description = field.NewString(tableName, "description")
	_designGuide.Content = field.NewString(tableName, "content")
	_designGuide.CreatedBy = field.NewInt64(tableName, "created_by")
	_designGuide.CreatedAt = field.NewTime(tableName, "created_at")
	_designGuide.UpdatedAt = field.NewTime(tableName, "updated_at")

	_designGuide.fillFieldMap()

	return _designGuide
}

type designGuide struct {
	designGuideDo designGuideDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Description field.String
	Content     field.String
	CreatedBy   field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (d designGuide) Table(newTableName string) *designGuide {
	d.designGuideDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d designGuide) As(alias string) *designGuide {
	d.designGuideDo.DO = *(d.designGuideDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *designGuide) updateTableName(table string) *designGuide {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Name = field.NewString(table, "name")
	d.Description = field.NewString(table, "description")
	d.Content = field.NewString(table, "content")
	d.CreatedBy = field.NewInt64(table, "created_by")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *designGuide) WithContext(ctx context.Context) IDesignGuideDo {
	return d.designGuideDo.WithContext(ctx)
}

func (d designGuide) TableName() string { return d.designGuideDo.TableName() }

func (d designGuide) Alias() string { return d.designGuideDo.Alias() }

func (d designGuide) Columns(cols ...field.Expr) gen.Columns { return d.designGuideDo.Columns(cols...) }

func (d *designGuide) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *designGuide) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["description"] = d.Description
	d.fieldMap["content"] = d.Content
	d.fieldMap["created_by"] = d.CreatedBy
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d designGuide) clone(db *gorm.DB) designGuide {
	d.designGuideDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d designGuide) replaceDB(db *gorm.DB) designGuide {
	d.designGuideDo.ReplaceDB(db)
	return d
}

type designGuideDo struct{ gen.DO }

type IDesignGuideDo interface {
	gen.SubQuery
	Debug() IDesignGuideDo
	WithContext(ctx context.Context) IDesignGuideDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDesignGuideDo
	WriteDB() IDesignGuideDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDesignGuideDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDesignGuideDo
	Not(conds ...gen.Condition) IDesignGuideDo
	Or(conds ...gen.Condition) IDesignGuideDo
	Select(conds ...field.Expr) IDesignGuideDo
	Where(conds ...gen.Condition) IDesignGuideDo
	Order(conds ...field.Expr) IDesignGuideDo
	Distinct(cols ...field.Expr) IDesignGuideDo
	Omit(cols ...field.Expr) IDesignGuideDo
	Join(table schema.Tabler, on ...field.Expr) IDesignGuideDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDesignGuideDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDesignGuideDo
	Group(cols ...field.Expr) IDesignGuideDo
	Having(conds ...gen.Condition) IDesignGuideDo
	Limit(limit int) IDesignGuideDo
	Offset(offset int) IDesignGuideDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDesignGuideDo
	Unscoped() IDesignGuideDo
	Create(values ...*entity.DesignGuide) error
	CreateInBatches(values []*entity.DesignGuide, batchSize int) error
	Save(values ...*entity.DesignGuide) error
	First() (*entity.DesignGuide, error)
	Take() (*entity.DesignGuide, error)
	Last() (*entity.DesignGuide, error)
	Find() ([]*entity.DesignGuide, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.DesignGuide, err error)
	FindInBatches(result *[]*entity.DesignGuide, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.DesignGuide) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDesignGuideDo
	Assign(attrs ...field.AssignExpr) IDesignGuideDo
	Joins(fields ...field.RelationField) IDesignGuideDo
	Preload(fields ...field.RelationField) IDesignGuideDo
	FirstOrInit() (*entity.DesignGuide, error)
	FirstOrCreate() (*entity.DesignGuide, error)
	FindByPage(offset int, limit int) (result []*entity.DesignGuide, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDesignGuideDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d designGuideDo) Debug() IDesignGuideDo {
	return d.withDO(d.DO.Debug())
}

func (d designGuideDo) WithContext(ctx context.Context) IDesignGuideDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d designGuideDo) ReadDB() IDesignGuideDo {
	return d.Clauses(dbresolver.Read)
}

func (d designGuideDo) WriteDB() IDesignGuideDo {
	return d.Clauses(dbresolver.Write)
}

func (d designGuideDo) Session(config *gorm.Session) IDesignGuideDo {
	return d.withDO(d.DO.Session(config))
}

func (d designGuideDo) Clauses(conds ...clause.Expression) IDesignGuideDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d designGuideDo) Returning(value interface{}, columns ...string) IDesignGuideDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d designGuideDo) Not(conds ...gen.Condition) IDesignGuideDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d designGuideDo) Or(conds ...gen.Condition) IDesignGuideDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d designGuideDo) Select(conds ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d designGuideDo) Where(conds ...gen.Condition) IDesignGuideDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d designGuideDo) Order(conds ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d designGuideDo) Distinct(cols ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d designGuideDo) Omit(cols ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d designGuideDo) Join(table schema.Tabler, on ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d designGuideDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d designGuideDo) RightJoin(table schema.Tabler, on ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d designGuideDo) Group(cols ...field.Expr) IDesignGuideDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d designGuideDo) Having(conds ...gen.Condition) IDesignGuideDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d designGuideDo) Limit(limit int) IDesignGuideDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d designGuideDo) Offset(offset int) IDesignGuideDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d designGuideDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDesignGuideDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d designGuideDo) Unscoped() IDesignGuideDo {
	return d.withDO(d.DO.Unscoped())
}

func (d designGuideDo) Create(values ...*entity.DesignGuide) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d designGuideDo) CreateInBatches(values []*entity.DesignGuide, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d designGuideDo) Save(values ...*entity.DesignGuide) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d designGuideDo) First() (*entity.DesignGuide, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuide), nil
	}
}

func (d designGuideDo) Take() (*entity.DesignGuide, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuide), nil
	}
}

func (d designGuideDo) Last() (*entity.DesignGuide, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuide), nil
	}
}

func (d designGuideDo) Find() ([]*entity.DesignGuide, error) {
	result, err := d.DO.Find()
	return result.([]*entity.DesignGuide), err
}

func (d designGuideDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.DesignGuide, err error) {
	buf := make([]*entity.DesignGuide, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d designGuideDo) FindInBatches(result *[]*entity.DesignGuide, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d designGuideDo) Attrs(attrs ...field.AssignExpr) IDesignGuideDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d designGuideDo) Assign(attrs ...field.AssignExpr) IDesignGuideDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d designGuideDo) Joins(fields ...field.RelationField) IDesignGuideDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d designGuideDo) Preload(fields ...field.RelationField) IDesignGuideDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d designGuideDo) FirstOrInit() (*entity.DesignGuide, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuide), nil
	}
}

func (d designGuideDo) FirstOrCreate() (*entity.DesignGuide, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DesignGuide), nil
	}
}

func (d designGuideDo) FindByPage(offset int, limit int) (result []*entity.DesignGuide, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d designGuideDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d designGuideDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d designGuideDo) Delete(models ...*entity.DesignGuide) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *designGuideDo) withDO(do gen.Dao) *designGuideDo {
	d.DO = *do.(*gen.DO)
	return d
}
