// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newEdge(db *gorm.DB, opts ...gen.DOOption) edge {
	_edge := edge{}

	_edge.edgeDo.UseDB(db, opts...)
	_edge.edgeDo.UseModel(&entity.Edge{})

	tableName := _edge.edgeDo.TableName()
	_edge.ALL = field.NewAsterisk(tableName)
	_edge.ID = field.NewInt64(tableName, "id")
	_edge.VariantID = field.NewInt64(tableName, "variant_id")
	_edge.FromNodeID = field.NewInt64(tableName, "from_node_id")
	_edge.ToNodeID = field.NewInt64(tableName, "to_node_id")
	_edge.Kind = field.NewString(tableName, "kind")
	_edge.Style = field.NewString(tableName, "style")
	_edge.Label = field.NewString(tableName, "label")
	_edge.Metadata = field.NewField(tableName, "metadata")
	_edge.CreatedAt = field.NewTime(tableName, "created_at")

	_edge.fillFieldMap()

	return _edge
}

type edge struct {
	edgeDo edgeDo

	ALL        field.Asterisk
	ID         field.Int64
	VariantID  field.Int64
	FromNodeID field.Int64
	ToNodeID   field.Int64
	Kind       field.String
	Style      field.String
	Label      field.String
	Metadata   field.Field
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (e edge) Table(newTableName string) *edge {
	e.edgeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e edge) As(alias string) *edge {
	e.edgeDo.DO = *(e.edgeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *edge) updateTableName(table string) *edge {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.VariantID = field.NewInt64(table, "variant_id")
	e.FromNodeID = field.NewInt64(table, "from_node_id")
	e.ToNodeID = field.NewInt64(table, "to_node_id")
	e.Kind = field.NewString(table, "kind")
	e.Style = field.NewString(table, "style")
	e.Label = field.NewString(table, "label")
	e.Metadata = field.NewField(table, "metadata")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *edge) WithContext(ctx context.Context) IEdgeDo { return e.edgeDo.WithContext(ctx) }

func (e edge) TableName() string { return e.edgeDo.TableName() }

func (e edge) Alias() string { return e.edgeDo.Alias() }

func (e edge) Columns(cols ...field.Expr) gen.Columns { return e.edgeDo.Columns(cols...) }

func (e *edge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *edge) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["variant_id"] = e.VariantID
	e.fieldMap["from_node_id"] = e.FromNodeID
	e.fieldMap["to_node_id"] = e.ToNodeID
	e.fieldMap["kind"] = e.Kind
	e.fieldMap["style"] = e.Style
	e.fieldMap["label"] = e.Label
	e.fieldMap["metadata"] = e.Metadata
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e edge) clone(db *gorm.DB) edge {
	e.edgeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e edge) replaceDB(db *gorm.DB) edge {
	e.edgeDo.ReplaceDB(db)
	return e
}

type edgeDo struct{ gen.DO }

type IEdgeDo interface {
	gen.SubQuery
	Debug() IEdgeDo
	WithContext(ctx context.Context) IEdgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEdgeDo
	WriteDB() IEdgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEdgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEdgeDo
	Not(conds ...gen.Condition) IEdgeDo
	Or(conds ...gen.Condition) IEdgeDo
	Select(conds ...field.Expr) IEdgeDo
	Where(conds ...gen.Condition) IEdgeDo
	Order(conds ...field.Expr) IEdgeDo
	Distinct(cols ...field.Expr) IEdgeDo
	Omit(cols ...field.Expr) IEdgeDo
	Join(table schema.Tabler, on ...field.Expr) IEdgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEdgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEdgeDo
	Group(cols ...field.Expr) IEdgeDo
	Having(conds ...gen.Condition) IEdgeDo
	Limit(limit int) IEdgeDo
	Offset(offset int) IEdgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEdgeDo
	Unscoped() IEdgeDo
	Create(values ...*entity.Edge) error
	CreateInBatches(values []*entity.Edge, batchSize int) error
	Save(values ...*entity.Edge) error
	First() (*entity.Edge, error)
	Take() (*entity.Edge, error)
	Last() (*entity.Edge, error)
	Find() ([]*entity.Edge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Edge, err error)
	FindInBatches(result *[]*entity.Edge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Edge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEdgeDo
	Assign(attrs ...field.AssignExpr) IEdgeDo
	Joins(fields ...field.RelationField) IEdgeDo
	Preload(fields ...field.RelationField) IEdgeDo
	FirstOrInit() (*entity.Edge, error)
	FirstOrCreate() (*entity.Edge, error)
	FindByPage(offset int, limit int) (result []*entity.Edge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEdgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e edgeDo) Debug() IEdgeDo {
	return e.withDO(e.DO.Debug())
}

func (e edgeDo) WithContext(ctx context.Context) IEdgeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e edgeDo) ReadDB() IEdgeDo {
	return e.Clauses(dbresolver.Read)
}

func (e edgeDo) WriteDB() IEdgeDo {
	return e.Clauses(dbresolver.Write)
}

func (e edgeDo) Session(config *gorm.Session) IEdgeDo {
	return e.withDO(e.DO.Session(config))
}

func (e edgeDo) Clauses(conds ...clause.Expression) IEdgeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e edgeDo) Returning(value interface{}, columns ...string) IEdgeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e edgeDo) Not(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e edgeDo) Or(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e edgeDo) Select(conds ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e edgeDo) Where(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e edgeDo) Order(conds ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e edgeDo) Distinct(cols ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e edgeDo) Omit(cols ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e edgeDo) Join(table schema.Tabler, on ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e edgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e edgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e edgeDo) Group(cols ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e edgeDo) Having(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e edgeDo) Limit(limit int) IEdgeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e edgeDo) Offset(offset int) IEdgeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e edgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEdgeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e edgeDo) Unscoped() IEdgeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e edgeDo) Create(values ...*entity.Edge) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e edgeDo) CreateInBatches(values []*entity.Edge, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e edgeDo) Save(values ...*entity.Edge) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e edgeDo) First() (*entity.Edge, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Edge), nil
	}
}

func (e edgeDo) Take() (*entity.Edge, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Edge), nil
	}
}

func (e edgeDo) Last() (*entity.Edge, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Edge), nil
	}
}

func (e edgeDo) Find() ([]*entity.Edge, error) {
	result, err := e.DO.Find()
	return result.([]*entity.Edge), err
}

func (e edgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Edge, err error) {
	buf := make([]*entity.Edge, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e edgeDo) FindInBatches(result *[]*entity.Edge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e edgeDo) Attrs(attrs ...field.AssignExpr) IEdgeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e edgeDo) Assign(attrs ...field.AssignExpr) IEdgeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e edgeDo) Joins(fields ...field.RelationField) IEdgeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e edgeDo) Preload(fields ...field.RelationField) IEdgeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e edgeDo) FirstOrInit() (*entity.Edge, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Edge), nil
	}
}

func (e edgeDo) FirstOrCreate() (*entity.Edge, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Edge), nil
	}
}

func (e edgeDo) FindByPage(offset int, limit int) (result []*entity.Edge, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e edgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e edgeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e edgeDo) Delete(models ...*entity.Edge) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *edgeDo) withDO(do gen.Dao) *edgeDo {
	e.DO = *do.(*gen.DO)
	return e
}
