// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	ActivityLog     *activityLog
	AnalysisReport  *analysisReport
	DesignGuide     *designGuide
	DesignGuideLike *designGuideLike
	Edge            *edge
	Node            *node
	Project         *project
	ProjectMember   *projectMember
	User            *user
	Variant         *variant
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ActivityLog = &Q.ActivityLog
	AnalysisReport = &Q.AnalysisReport
	DesignGuide = &Q.DesignGuide
	DesignGuideLike = &Q.DesignGuideLike
	Edge = &Q.Edge
	Node = &Q.Node
	Project = &Q.Project
	ProjectMember = &Q.ProjectMember
	User = &Q.User
	Variant = &Q.Variant
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		ActivityLog:     newActivityLog(db, opts...),
		AnalysisReport:  newAnalysisReport(db, opts...),
		DesignGuide:     newDesignGuide(db, opts...),
		DesignGuideLike: newDesignGuideLike(db, opts...),
		Edge:            newEdge(db, opts...),
		Node:            newNode(db, opts...),
		Project:         newProject(db, opts...),
		ProjectMember:   newProjectMember(db, opts...),
		User:            newUser(db, opts...),
		Variant:         newVariant(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ActivityLog     activityLog
	AnalysisReport  analysisReport
	DesignGuide     designGuide
	DesignGuideLike designGuideLike
	Edge            edge
	Node            node
	Project         project
	ProjectMember   projectMember
	User            user
	Variant         variant
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ActivityLog:     q.ActivityLog.clone(db),
		AnalysisReport:  q.AnalysisReport.clone(db),
		DesignGuide:     q.DesignGuide.clone(db),
		DesignGuideLike: q.DesignGuideLike.clone(db),
		Edge:            q.Edge.clone(db),
		Node:            q.Node.clone(db),
		Project:         q.Project.clone(db),
		ProjectMember:   q.ProjectMember.clone(db),
		User:            q.User.clone(db),
		Variant:         q.Variant.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ActivityLog:     q.ActivityLog.replaceDB(db),
		AnalysisReport:  q.AnalysisReport.replaceDB(db),
		DesignGuide:     q.DesignGuide.replaceDB(db),
		DesignGuideLike: q.DesignGuideLike.replaceDB(db),
		Edge:            q.Edge.replaceDB(db),
		Node:            q.Node.replaceDB(db),
		Project:         q.Project.replaceDB(db),
		ProjectMember:   q.ProjectMember.replaceDB(db),
		User:            q.User.replaceDB(db),
		Variant:         q.Variant.replaceDB(db),
	}
}

type queryCtx struct {
	ActivityLog     IActivityLogDo
	AnalysisReport  IAnalysisReportDo
	DesignGuide     IDesignGuideDo
	DesignGuideLike IDesignGuideLikeDo
	Edge            IEdgeDo
	Node            INodeDo
	Project         IProjectDo
	ProjectMember   IProjectMemberDo
	User            IUserDo
	Variant         IVariantDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ActivityLog:     q.ActivityLog.WithContext(ctx),
		AnalysisReport:  q.AnalysisReport.WithContext(ctx),
		DesignGuide:     q.DesignGuide.WithContext(ctx),
		DesignGuideLike: q.DesignGuideLike.WithContext(ctx),
		Edge:            q.Edge.WithContext(ctx),
		Node:            q.Node.WithContext(ctx),
		Project:         q.Project.WithContext(ctx),
		ProjectMember:   q.ProjectMember.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		Variant:         q.Variant.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
