// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newGraphBuildJob(db *gorm.DB, opts ...gen.DOOption) graphBuildJob {
	_graphBuildJob := graphBuildJob{}

	_graphBuildJob.graphBuildJobDo.UseDB(db, opts...)
	_graphBuildJob.graphBuildJobDo.UseModel(&entity.GraphBuildJob{})

	tableName := _graphBuildJob.graphBuildJobDo.TableName()
	_graphBuildJob.ALL = field.NewAsterisk(tableName)
	_graphBuildJob.ID = field.NewInt64(tableName, "id")
	_graphBuildJob.VariantID = field.NewInt64(tableName, "variant_id")
	_graphBuildJob.RequestedBy = field.NewInt64(tableName, "requested_by")
	_graphBuildJob.Status = field.NewString(tableName, "status")
	_graphBuildJob.ErrorMessage = field.NewString(tableName, "error_message")
	_graphBuildJob.StartedAt = field.NewTime(tableName, "started_at")
	_graphBuildJob.FinishedAt = field.NewTime(tableName, "finished_at")
	_graphBuildJob.CreatedAt = field.NewTime(tableName, "created_at")

	_graphBuildJob.fillFieldMap()

	return _graphBuildJob
}

type graphBuildJob struct {
	graphBuildJobDo graphBuildJobDo

	ALL          field.Asterisk
	ID           field.Int64
	VariantID    field.Int64
	RequestedBy  field.Int64
	Status       field.String
	ErrorMessage field.String
	StartedAt    field.Time
	FinishedAt   field.Time
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (g graphBuildJob) Table(newTableName string) *graphBuildJob {
	g.graphBuildJobDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g graphBuildJob) As(alias string) *graphBuildJob {
	g.graphBuildJobDo.DO = *(g.graphBuildJobDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *graphBuildJob) updateTableName(table string) *graphBuildJob {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.VariantID = field.NewInt64(table, "variant_id")
	g.RequestedBy = field.NewInt64(table, "requested_by")
	g.Status = field.NewString(table, "status")
	g.ErrorMessage = field.NewString(table, "error_message")
	g.StartedAt = field.NewTime(table, "started_at")
	g.FinishedAt = field.NewTime(table, "finished_at")
	g.CreatedAt = field.NewTime(table, "created_at")

	g.fillFieldMap()

	return g
}

func (g *graphBuildJob) WithContext(ctx context.Context) IGraphBuildJobDo {
	return g.graphBuildJobDo.WithContext(ctx)
}

func (g graphBuildJob) TableName() string { return g.graphBuildJobDo.TableName() }

func (g graphBuildJob) Alias() string { return g.graphBuildJobDo.Alias() }

func (g graphBuildJob) Columns(cols ...field.Expr) gen.Columns {
	return g.graphBuildJobDo.Columns(cols...)
}

func (g *graphBuildJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *graphBuildJob) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["variant_id"] = g.VariantID
	g.fieldMap["requested_by"] = g.RequestedBy
	g.fieldMap["status"] = g.Status
	g.fieldMap["error_message"] = g.ErrorMessage
	g.fieldMap["started_at"] = g.StartedAt
	g.fieldMap["finished_at"] = g.FinishedAt
	g.fieldMap["created_at"] = g.CreatedAt
}

func (g graphBuildJob) clone(db *gorm.DB) graphBuildJob {
	g.graphBuildJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g graphBuildJob) replaceDB(db *gorm.DB) graphBuildJob {
	g.graphBuildJobDo.ReplaceDB(db)
	return g
}

type graphBuildJobDo struct{ gen.DO }

type IGraphBuildJobDo interface {
	gen.SubQuery
	Debug() IGraphBuildJobDo
	WithContext(ctx context.Context) IGraphBuildJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGraphBuildJobDo
	WriteDB() IGraphBuildJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGraphBuildJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGraphBuildJobDo
	Not(conds ...gen.Condition) IGraphBuildJobDo
	Or(conds ...gen.Condition) IGraphBuildJobDo
	Select(conds ...field.Expr) IGraphBuildJobDo
	Where(conds ...gen.Condition) IGraphBuildJobDo
	Order(conds ...field.Expr) IGraphBuildJobDo
	Distinct(cols ...field.Expr) IGraphBuildJobDo
	Omit(cols ...field.Expr) IGraphBuildJobDo
	Join(table schema.Tabler, on ...field.Expr) IGraphBuildJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGraphBuildJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGraphBuildJobDo
	Group(cols ...field.Expr) IGraphBuildJobDo
	Having(conds ...gen.Condition) IGraphBuildJobDo
	Limit(limit int) IGraphBuildJobDo
	Offset(offset int) IGraphBuildJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphBuildJobDo
	Unscoped() IGraphBuildJobDo
	Create(values ...*entity.GraphBuildJob) error
	CreateInBatches(values []*entity.GraphBuildJob, batchSize int) error
	Save(values ...*entity.GraphBuildJob) error
	First() (*entity.GraphBuildJob, error)
	Take() (*entity.GraphBuildJob, error)
	Last() (*entity.GraphBuildJob, error)
	Find() ([]*entity.GraphBuildJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.GraphBuildJob, err error)
	FindInBatches(result *[]*entity.GraphBuildJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.GraphBuildJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGraphBuildJobDo
	Assign(attrs ...field.AssignExpr) IGraphBuildJobDo
	Joins(fields ...field.RelationField) IGraphBuildJobDo
	Preload(fields ...field.RelationField) IGraphBuildJobDo
	FirstOrInit() (*entity.GraphBuildJob, error)
	FirstOrCreate() (*entity.GraphBuildJob, error)
	FindByPage(offset int, limit int) (result []*entity.GraphBuildJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGraphBuildJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g graphBuildJobDo) Debug() IGraphBuildJobDo {
	return g.withDO(g.DO.Debug())
}

func (g graphBuildJobDo) WithContext(ctx context.Context) IGraphBuildJobDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g graphBuildJobDo) ReadDB() IGraphBuildJobDo {
	return g.Clauses(dbresolver.Read)
}

func (g graphBuildJobDo) WriteDB() IGraphBuildJobDo {
	return g.Clauses(dbresolver.Write)
}

func (g graphBuildJobDo) Session(config *gorm.Session) IGraphBuildJobDo {
	return g.withDO(g.DO.Session(config))
}

func (g graphBuildJobDo) Clauses(conds ...clause.Expression) IGraphBuildJobDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g graphBuildJobDo) Returning(value interface{}, columns ...string) IGraphBuildJobDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g graphBuildJobDo) Not(conds ...gen.Condition) IGraphBuildJobDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g graphBuildJobDo) Or(conds ...gen.Condition) IGraphBuildJobDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g graphBuildJobDo) Select(conds ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g graphBuildJobDo) Where(conds ...gen.Condition) IGraphBuildJobDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g graphBuildJobDo) Order(conds ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g graphBuildJobDo) Distinct(cols ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g graphBuildJobDo) Omit(cols ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g graphBuildJobDo) Join(table schema.Tabler, on ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g graphBuildJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g graphBuildJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g graphBuildJobDo) Group(cols ...field.Expr) IGraphBuildJobDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g graphBuildJobDo) Having(conds ...gen.Condition) IGraphBuildJobDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g graphBuildJobDo) Limit(limit int) IGraphBuildJobDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g graphBuildJobDo) Offset(offset int) IGraphBuildJobDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g graphBuildJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphBuildJobDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g graphBuildJobDo) Unscoped() IGraphBuildJobDo {
	return g.withDO(g.DO.Unscoped())
}

func (g graphBuildJobDo) Create(values ...*entity.GraphBuildJob) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g graphBuildJobDo) CreateInBatches(values []*entity.GraphBuildJob, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g graphBuildJobDo) Save(values ...*entity.GraphBuildJob) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g graphBuildJobDo) First() (*entity.GraphBuildJob, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.GraphBuildJob), nil
	}
}

func (g graphBuildJobDo) Take() (*entity.GraphBuildJob, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.GraphBuildJob), nil
	}
}

func (g graphBuildJobDo) Last() (*entity.GraphBuildJob, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.GraphBuildJob), nil
	}
}

func (g graphBuildJobDo) Find() ([]*entity.GraphBuildJob, error) {
	result, err := g.DO.Find()
	return result.([]*entity.GraphBuildJob), err
}

func (g graphBuildJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.GraphBuildJob, err error) {
	buf := make([]*entity.GraphBuildJob, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g graphBuildJobDo) FindInBatches(result *[]*entity.GraphBuildJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g graphBuildJobDo) Attrs(attrs ...field.AssignExpr) IGraphBuildJobDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g graphBuildJobDo) Assign(attrs ...field.AssignExpr) IGraphBuildJobDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g graphBuildJobDo) Joins(fields ...field.RelationField) IGraphBuildJobDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g graphBuildJobDo) Preload(fields ...field.RelationField) IGraphBuildJobDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g graphBuildJobDo) FirstOrInit() (*entity.GraphBuildJob, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.GraphBuildJob), nil
	}
}

func (g graphBuildJobDo) FirstOrCreate() (*entity.GraphBuildJob, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.GraphBuildJob), nil
	}
}

func (g graphBuildJobDo) FindByPage(offset int, limit int) (result []*entity.GraphBuildJob, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g graphBuildJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g graphBuildJobDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g graphBuildJobDo) Delete(models ...*entity.GraphBuildJob) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *graphBuildJobDo) withDO(do gen.Dao) *graphBuildJobDo {
	g.DO = *do.(*gen.DO)
	return g
}
