// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newLayoutJob(db *gorm.DB, opts ...gen.DOOption) layoutJob {
	_layoutJob := layoutJob{}

	_layoutJob.layoutJobDo.UseDB(db, opts...)
	_layoutJob.layoutJobDo.UseModel(&entity.LayoutJob{})

	tableName := _layoutJob.layoutJobDo.TableName()
	_layoutJob.ALL = field.NewAsterisk(tableName)
	_layoutJob.ID = field.NewInt64(tableName, "id")
	_layoutJob.VariantID = field.NewInt64(tableName, "variant_id")
	_layoutJob.RequestedBy = field.NewInt64(tableName, "requested_by")
	_layoutJob.LayoutType = field.NewString(tableName, "layout_type")
	_layoutJob.Status = field.NewString(tableName, "status")
	_layoutJob.ErrorMessage = field.NewString(tableName, "error_message")
	_layoutJob.StartedAt = field.NewTime(tableName, "started_at")
	_layoutJob.FinishedAt = field.NewTime(tableName, "finished_at")
	_layoutJob.CreatedAt = field.NewTime(tableName, "created_at")

	_layoutJob.fillFieldMap()

	return _layoutJob
}

type layoutJob struct {
	layoutJobDo layoutJobDo

	ALL          field.Asterisk
	ID           field.Int64
	VariantID    field.Int64
	RequestedBy  field.Int64
	LayoutType   field.String
	Status       field.String
	ErrorMessage field.String
	StartedAt    field.Time
	FinishedAt   field.Time
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (l layoutJob) Table(newTableName string) *layoutJob {
	l.layoutJobDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l layoutJob) As(alias string) *layoutJob {
	l.layoutJobDo.DO = *(l.layoutJobDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *layoutJob) updateTableName(table string) *layoutJob {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.VariantID = field.NewInt64(table, "variant_id")
	l.RequestedBy = field.NewInt64(table, "requested_by")
	l.LayoutType = field.NewString(table, "layout_type")
	l.Status = field.NewString(table, "status")
	l.ErrorMessage = field.NewString(table, "error_message")
	l.StartedAt = field.NewTime(table, "started_at")
	l.FinishedAt = field.NewTime(table, "finished_at")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *layoutJob) WithContext(ctx context.Context) ILayoutJobDo {
	return l.layoutJobDo.WithContext(ctx)
}

func (l layoutJob) TableName() string { return l.layoutJobDo.TableName() }

func (l layoutJob) Alias() string { return l.layoutJobDo.Alias() }

func (l layoutJob) Columns(cols ...field.Expr) gen.Columns { return l.layoutJobDo.Columns(cols...) }

func (l *layoutJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *layoutJob) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 9)
	l.fieldMap["id"] = l.ID
	l.fieldMap["variant_id"] = l.VariantID
	l.fieldMap["requested_by"] = l.RequestedBy
	l.fieldMap["layout_type"] = l.LayoutType
	l.fieldMap["status"] = l.Status
	l.fieldMap["error_message"] = l.ErrorMessage
	l.fieldMap["started_at"] = l.StartedAt
	l.fieldMap["finished_at"] = l.FinishedAt
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l layoutJob) clone(db *gorm.DB) layoutJob {
	l.layoutJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l layoutJob) replaceDB(db *gorm.DB) layoutJob {
	l.layoutJobDo.ReplaceDB(db)
	return l
}

type layoutJobDo struct{ gen.DO }

type ILayoutJobDo interface {
	gen.SubQuery
	Debug() ILayoutJobDo
	WithContext(ctx context.Context) ILayoutJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILayoutJobDo
	WriteDB() ILayoutJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILayoutJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILayoutJobDo
	Not(conds ...gen.Condition) ILayoutJobDo
	Or(conds ...gen.Condition) ILayoutJobDo
	Select(conds ...field.Expr) ILayoutJobDo
	Where(conds ...gen.Condition) ILayoutJobDo
	Order(conds ...field.Expr) ILayoutJobDo
	Distinct(cols ...field.Expr) ILayoutJobDo
	Omit(cols ...field.Expr) ILayoutJobDo
	Join(table schema.Tabler, on ...field.Expr) ILayoutJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILayoutJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILayoutJobDo
	Group(cols ...field.Expr) ILayoutJobDo
	Having(conds ...gen.Condition) ILayoutJobDo
	Limit(limit int) ILayoutJobDo
	Offset(offset int) ILayoutJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILayoutJobDo
	Unscoped() ILayoutJobDo
	Create(values ...*entity.LayoutJob) error
	CreateInBatches(values []*entity.LayoutJob, batchSize int) error
	Save(values ...*entity.LayoutJob) error
	First() (*entity.LayoutJob, error)
	Take() (*entity.LayoutJob, error)
	Last() (*entity.LayoutJob, error)
	Find() ([]*entity.LayoutJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.LayoutJob, err error)
	FindInBatches(result *[]*entity.LayoutJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.LayoutJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILayoutJobDo
	Assign(attrs ...field.AssignExpr) ILayoutJobDo
	Joins(fields ...field.RelationField) ILayoutJobDo
	Preload(fields ...field.RelationField) ILayoutJobDo
	FirstOrInit() (*entity.LayoutJob, error)
	FirstOrCreate() (*entity.LayoutJob, error)
	FindByPage(offset int, limit int) (result []*entity.LayoutJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILayoutJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l layoutJobDo) Debug() ILayoutJobDo {
	return l.withDO(l.DO.Debug())
}

func (l layoutJobDo) WithContext(ctx context.Context) ILayoutJobDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l layoutJobDo) ReadDB() ILayoutJobDo {
	return l.Clauses(dbresolver.Read)
}

func (l layoutJobDo) WriteDB() ILayoutJobDo {
	return l.Clauses(dbresolver.Write)
}

func (l layoutJobDo) Session(config *gorm.Session) ILayoutJobDo {
	return l.withDO(l.DO.Session(config))
}

func (l layoutJobDo) Clauses(conds ...clause.Expression) ILayoutJobDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l layoutJobDo) Returning(value interface{}, columns ...string) ILayoutJobDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l layoutJobDo) Not(conds ...gen.Condition) ILayoutJobDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l layoutJobDo) Or(conds ...gen.Condition) ILayoutJobDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l layoutJobDo) Select(conds ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l layoutJobDo) Where(conds ...gen.Condition) ILayoutJobDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l layoutJobDo) Order(conds ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l layoutJobDo) Distinct(cols ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l layoutJobDo) Omit(cols ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l layoutJobDo) Join(table schema.Tabler, on ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l layoutJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l layoutJobDo) RightJoin(table schema.Tabler, on ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l layoutJobDo) Group(cols ...field.Expr) ILayoutJobDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l layoutJobDo) Having(conds ...gen.Condition) ILayoutJobDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l layoutJobDo) Limit(limit int) ILayoutJobDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l layoutJobDo) Offset(offset int) ILayoutJobDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l layoutJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILayoutJobDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l layoutJobDo) Unscoped() ILayoutJobDo {
	return l.withDO(l.DO.Unscoped())
}

func (l layoutJobDo) Create(values ...*entity.LayoutJob) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l layoutJobDo) CreateInBatches(values []*entity.LayoutJob, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l layoutJobDo) Save(values ...*entity.LayoutJob) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l layoutJobDo) First() (*entity.LayoutJob, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.LayoutJob), nil
	}
}

func (l layoutJobDo) Take() (*entity.LayoutJob, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.LayoutJob), nil
	}
}

func (l layoutJobDo) Last() (*entity.LayoutJob, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.LayoutJob), nil
	}
}

func (l layoutJobDo) Find() ([]*entity.LayoutJob, error) {
	result, err := l.DO.Find()
	return result.([]*entity.LayoutJob), err
}

func (l layoutJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.LayoutJob, err error) {
	buf := make([]*entity.LayoutJob, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l layoutJobDo) FindInBatches(result *[]*entity.LayoutJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l layoutJobDo) Attrs(attrs ...field.AssignExpr) ILayoutJobDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l layoutJobDo) Assign(attrs ...field.AssignExpr) ILayoutJobDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l layoutJobDo) Joins(fields ...field.RelationField) ILayoutJobDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l layoutJobDo) Preload(fields ...field.RelationField) ILayoutJobDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l layoutJobDo) FirstOrInit() (*entity.LayoutJob, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.LayoutJob), nil
	}
}

func (l layoutJobDo) FirstOrCreate() (*entity.LayoutJob, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.LayoutJob), nil
	}
}

func (l layoutJobDo) FindByPage(offset int, limit int) (result []*entity.LayoutJob, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l layoutJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l layoutJobDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l layoutJobDo) Delete(models ...*entity.LayoutJob) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *layoutJobDo) withDO(do gen.Dao) *layoutJobDo {
	l.DO = *do.(*gen.DO)
	return l
}
