// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newNode(db *gorm.DB, opts ...gen.DOOption) node {
	_node := node{}

	_node.nodeDo.UseDB(db, opts...)
	_node.nodeDo.UseModel(&entity.Node{})

	tableName := _node.nodeDo.TableName()
	_node.ALL = field.NewAsterisk(tableName)
	_node.ID = field.NewInt64(tableName, "id")
	_node.VariantID = field.NewInt64(tableName, "variant_id")
	_node.Kind = field.NewString(tableName, "kind")
	_node.Title = field.NewString(tableName, "title")
	_node.FilePath = field.NewString(tableName, "file_path")
	_node.Signature = field.NewString(tableName, "signature")
	_node.Receiver = field.NewString(tableName, "receiver")
	_node.CodeText = field.NewString(tableName, "code_text")
	_node.PositionX = field.NewFloat64(tableName, "position_x")
	_node.PositionY = field.NewFloat64(tableName, "position_y")
	_node.Metadata = field.NewField(tableName, "metadata")
	_node.CreatedAt = field.NewTime(tableName, "created_at")
	_node.UpdatedAt = field.NewTime(tableName, "updated_at")

	_node.fillFieldMap()

	return _node
}

type node struct {
	nodeDo nodeDo

	ALL       field.Asterisk
	ID        field.Int64
	VariantID field.Int64
	Kind      field.String
	Title     field.String
	FilePath  field.String
	Signature field.String
	Receiver  field.String
	CodeText  field.String
	PositionX field.Float64
	PositionY field.Float64
	Metadata  field.Field
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (n node) Table(newTableName string) *node {
	n.nodeDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n node) As(alias string) *node {
	n.nodeDo.DO = *(n.nodeDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *node) updateTableName(table string) *node {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.VariantID = field.NewInt64(table, "variant_id")
	n.Kind = field.NewString(table, "kind")
	n.Title = field.NewString(table, "title")
	n.FilePath = field.NewString(table, "file_path")
	n.Signature = field.NewString(table, "signature")
	n.Receiver = field.NewString(table, "receiver")
	n.CodeText = field.NewString(table, "code_text")
	n.PositionX = field.NewFloat64(table, "position_x")
	n.PositionY = field.NewFloat64(table, "position_y")
	n.Metadata = field.NewField(table, "metadata")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *node) WithContext(ctx context.Context) INodeDo { return n.nodeDo.WithContext(ctx) }

func (n node) TableName() string { return n.nodeDo.TableName() }

func (n node) Alias() string { return n.nodeDo.Alias() }

func (n node) Columns(cols ...field.Expr) gen.Columns { return n.nodeDo.Columns(cols...) }

func (n *node) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *node) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["variant_id"] = n.VariantID
	n.fieldMap["kind"] = n.Kind
	n.fieldMap["title"] = n.Title
	n.fieldMap["file_path"] = n.FilePath
	n.fieldMap["signature"] = n.Signature
	n.fieldMap["receiver"] = n.Receiver
	n.fieldMap["code_text"] = n.CodeText
	n.fieldMap["position_x"] = n.PositionX
	n.fieldMap["position_y"] = n.PositionY
	n.fieldMap["metadata"] = n.Metadata
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n node) clone(db *gorm.DB) node {
	n.nodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n node) replaceDB(db *gorm.DB) node {
	n.nodeDo.ReplaceDB(db)
	return n
}

type nodeDo struct{ gen.DO }

type INodeDo interface {
	gen.SubQuery
	Debug() INodeDo
	WithContext(ctx context.Context) INodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeDo
	WriteDB() INodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeDo
	Not(conds ...gen.Condition) INodeDo
	Or(conds ...gen.Condition) INodeDo
	Select(conds ...field.Expr) INodeDo
	Where(conds ...gen.Condition) INodeDo
	Order(conds ...field.Expr) INodeDo
	Distinct(cols ...field.Expr) INodeDo
	Omit(cols ...field.Expr) INodeDo
	Join(table schema.Tabler, on ...field.Expr) INodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeDo
	Group(cols ...field.Expr) INodeDo
	Having(conds ...gen.Condition) INodeDo
	Limit(limit int) INodeDo
	Offset(offset int) INodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeDo
	Unscoped() INodeDo
	Create(values ...*entity.Node) error
	CreateInBatches(values []*entity.Node, batchSize int) error
	Save(values ...*entity.Node) error
	First() (*entity.Node, error)
	Take() (*entity.Node, error)
	Last() (*entity.Node, error)
	Find() ([]*entity.Node, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Node, err error)
	FindInBatches(result *[]*entity.Node, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Node) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeDo
	Assign(attrs ...field.AssignExpr) INodeDo
	Joins(fields ...field.RelationField) INodeDo
	Preload(fields ...field.RelationField) INodeDo
	FirstOrInit() (*entity.Node, error)
	FirstOrCreate() (*entity.Node, error)
	FindByPage(offset int, limit int) (result []*entity.Node, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeDo) Debug() INodeDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeDo) WithContext(ctx context.Context) INodeDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeDo) ReadDB() INodeDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeDo) WriteDB() INodeDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeDo) Session(config *gorm.Session) INodeDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeDo) Clauses(conds ...clause.Expression) INodeDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeDo) Returning(value interface{}, columns ...string) INodeDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeDo) Not(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeDo) Or(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeDo) Select(conds ...field.Expr) INodeDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeDo) Where(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeDo) Order(conds ...field.Expr) INodeDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeDo) Distinct(cols ...field.Expr) INodeDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeDo) Omit(cols ...field.Expr) INodeDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeDo) Join(table schema.Tabler, on ...field.Expr) INodeDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeDo) Group(cols ...field.Expr) INodeDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeDo) Having(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeDo) Limit(limit int) INodeDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeDo) Offset(offset int) INodeDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeDo) Unscoped() INodeDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeDo) Create(values ...*entity.Node) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeDo) CreateInBatches(values []*entity.Node, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeDo) Save(values ...*entity.Node) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeDo) First() (*entity.Node, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Node), nil
	}
}

func (n nodeDo) Take() (*entity.Node, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Node), nil
	}
}

func (n nodeDo) Last() (*entity.Node, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Node), nil
	}
}

func (n nodeDo) Find() ([]*entity.Node, error) {
	result, err := n.DO.Find()
	return result.([]*entity.Node), err
}

func (n nodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Node, err error) {
	buf := make([]*entity.Node, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeDo) FindInBatches(result *[]*entity.Node, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeDo) Attrs(attrs ...field.AssignExpr) INodeDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeDo) Assign(attrs ...field.AssignExpr) INodeDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeDo) Joins(fields ...field.RelationField) INodeDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeDo) Preload(fields ...field.RelationField) INodeDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeDo) FirstOrInit() (*entity.Node, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Node), nil
	}
}

func (n nodeDo) FirstOrCreate() (*entity.Node, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Node), nil
	}
}

func (n nodeDo) FindByPage(offset int, limit int) (result []*entity.Node, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeDo) Delete(models ...*entity.Node) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeDo) withDO(do gen.Dao) *nodeDo {
	n.DO = *do.(*gen.DO)
	return n
}
