// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newProjectShare(db *gorm.DB, opts ...gen.DOOption) projectShare {
	_projectShare := projectShare{}

	_projectShare.projectShareDo.UseDB(db, opts...)
	_projectShare.projectShareDo.UseModel(&entity.ProjectShare{})

	tableName := _projectShare.projectShareDo.TableName()
	_projectShare.ALL = field.NewAsterisk(tableName)
	_projectShare.ID = field.NewInt64(tableName, "id")
	_projectShare.ProjectID = field.NewInt64(tableName, "project_id")
	_projectShare.TeamID = field.NewInt64(tableName, "team_id")
	_projectShare.SharedBy = field.NewInt64(tableName, "shared_by")
	_projectShare.SharedAt = field.NewTime(tableName, "shared_at")

	_projectShare.fillFieldMap()

	return _projectShare
}

type projectShare struct {
	projectShareDo projectShareDo

	ALL       field.Asterisk
	ID        field.Int64
	ProjectID field.Int64
	TeamID    field.Int64
	SharedBy  field.Int64
	SharedAt  field.Time

	fieldMap map[string]field.Expr
}

func (p projectShare) Table(newTableName string) *projectShare {
	p.projectShareDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p projectShare) As(alias string) *projectShare {
	p.projectShareDo.DO = *(p.projectShareDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *projectShare) updateTableName(table string) *projectShare {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ProjectID = field.NewInt64(table, "project_id")
	p.TeamID = field.NewInt64(table, "team_id")
	p.SharedBy = field.NewInt64(table, "shared_by")
	p.SharedAt = field.NewTime(table, "shared_at")

	p.fillFieldMap()

	return p
}

func (p *projectShare) WithContext(ctx context.Context) IProjectShareDo {
	return p.projectShareDo.WithContext(ctx)
}

func (p projectShare) TableName() string { return p.projectShareDo.TableName() }

func (p projectShare) Alias() string { return p.projectShareDo.Alias() }

func (p projectShare) Columns(cols ...field.Expr) gen.Columns {
	return p.projectShareDo.Columns(cols...)
}

func (p *projectShare) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *projectShare) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["project_id"] = p.ProjectID
	p.fieldMap["team_id"] = p.TeamID
	p.fieldMap["shared_by"] = p.SharedBy
	p.fieldMap["shared_at"] = p.SharedAt
}

func (p projectShare) clone(db *gorm.DB) projectShare {
	p.projectShareDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p projectShare) replaceDB(db *gorm.DB) projectShare {
	p.projectShareDo.ReplaceDB(db)
	return p
}

type projectShareDo struct{ gen.DO }

type IProjectShareDo interface {
	gen.SubQuery
	Debug() IProjectShareDo
	WithContext(ctx context.Context) IProjectShareDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProjectShareDo
	WriteDB() IProjectShareDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProjectShareDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProjectShareDo
	Not(conds ...gen.Condition) IProjectShareDo
	Or(conds ...gen.Condition) IProjectShareDo
	Select(conds ...field.Expr) IProjectShareDo
	Where(conds ...gen.Condition) IProjectShareDo
	Order(conds ...field.Expr) IProjectShareDo
	Distinct(cols ...field.Expr) IProjectShareDo
	Omit(cols ...field.Expr) IProjectShareDo
	Join(table schema.Tabler, on ...field.Expr) IProjectShareDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProjectShareDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProjectShareDo
	Group(cols ...field.Expr) IProjectShareDo
	Having(conds ...gen.Condition) IProjectShareDo
	Limit(limit int) IProjectShareDo
	Offset(offset int) IProjectShareDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectShareDo
	Unscoped() IProjectShareDo
	Create(values ...*entity.ProjectShare) error
	CreateInBatches(values []*entity.ProjectShare, batchSize int) error
	Save(values ...*entity.ProjectShare) error
	First() (*entity.ProjectShare, error)
	Take() (*entity.ProjectShare, error)
	Last() (*entity.ProjectShare, error)
	Find() ([]*entity.ProjectShare, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ProjectShare, err error)
	FindInBatches(result *[]*entity.ProjectShare, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ProjectShare) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProjectShareDo
	Assign(attrs ...field.AssignExpr) IProjectShareDo
	Joins(fields ...field.RelationField) IProjectShareDo
	Preload(fields ...field.RelationField) IProjectShareDo
	FirstOrInit() (*entity.ProjectShare, error)
	FirstOrCreate() (*entity.ProjectShare, error)
	FindByPage(offset int, limit int) (result []*entity.ProjectShare, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProjectShareDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p projectShareDo) Debug() IProjectShareDo {
	return p.withDO(p.DO.Debug())
}

func (p projectShareDo) WithContext(ctx context.Context) IProjectShareDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectShareDo) ReadDB() IProjectShareDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectShareDo) WriteDB() IProjectShareDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectShareDo) Session(config *gorm.Session) IProjectShareDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectShareDo) Clauses(conds ...clause.Expression) IProjectShareDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectShareDo) Returning(value interface{}, columns ...string) IProjectShareDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectShareDo) Not(conds ...gen.Condition) IProjectShareDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectShareDo) Or(conds ...gen.Condition) IProjectShareDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectShareDo) Select(conds ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectShareDo) Where(conds ...gen.Condition) IProjectShareDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectShareDo) Order(conds ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectShareDo) Distinct(cols ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectShareDo) Omit(cols ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectShareDo) Join(table schema.Tabler, on ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectShareDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectShareDo) RightJoin(table schema.Tabler, on ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectShareDo) Group(cols ...field.Expr) IProjectShareDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectShareDo) Having(conds ...gen.Condition) IProjectShareDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectShareDo) Limit(limit int) IProjectShareDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectShareDo) Offset(offset int) IProjectShareDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectShareDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectShareDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectShareDo) Unscoped() IProjectShareDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectShareDo) Create(values ...*entity.ProjectShare) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectShareDo) CreateInBatches(values []*entity.ProjectShare, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectShareDo) Save(values ...*entity.ProjectShare) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectShareDo) First() (*entity.ProjectShare, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ProjectShare), nil
	}
}

func (p projectShareDo) Take() (*entity.ProjectShare, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ProjectShare), nil
	}
}

func (p projectShareDo) Last() (*entity.ProjectShare, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ProjectShare), nil
	}
}

func (p projectShareDo) Find() ([]*entity.ProjectShare, error) {
	result, err := p.DO.Find()
	return result.([]*entity.ProjectShare), err
}

func (p projectShareDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ProjectShare, err error) {
	buf := make([]*entity.ProjectShare, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectShareDo) FindInBatches(result *[]*entity.ProjectShare, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectShareDo) Attrs(attrs ...field.AssignExpr) IProjectShareDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectShareDo) Assign(attrs ...field.AssignExpr) IProjectShareDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectShareDo) Joins(fields ...field.RelationField) IProjectShareDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectShareDo) Preload(fields ...field.RelationField) IProjectShareDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectShareDo) FirstOrInit() (*entity.ProjectShare, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ProjectShare), nil
	}
}

func (p projectShareDo) FirstOrCreate() (*entity.ProjectShare, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ProjectShare), nil
	}
}

func (p projectShareDo) FindByPage(offset int, limit int) (result []*entity.ProjectShare, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectShareDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectShareDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectShareDo) Delete(models ...*entity.ProjectShare) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectShareDo) withDO(do gen.Dao) *projectShareDo {
	p.DO = *do.(*gen.DO)
	return p
}
