// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newReviewFeedbackTarget(db *gorm.DB, opts ...gen.DOOption) reviewFeedbackTarget {
	_reviewFeedbackTarget := reviewFeedbackTarget{}

	_reviewFeedbackTarget.reviewFeedbackTargetDo.UseDB(db, opts...)
	_reviewFeedbackTarget.reviewFeedbackTargetDo.UseModel(&entity.ReviewFeedbackTarget{})

	tableName := _reviewFeedbackTarget.reviewFeedbackTargetDo.TableName()
	_reviewFeedbackTarget.ALL = field.NewAsterisk(tableName)
	_reviewFeedbackTarget.ID = field.NewInt64(tableName, "id")
	_reviewFeedbackTarget.FeedbackID = field.NewInt64(tableName, "feedback_id")
	_reviewFeedbackTarget.TargetType = field.NewString(tableName, "target_type")
	_reviewFeedbackTarget.TargetRef = field.NewString(tableName, "target_ref")

	_reviewFeedbackTarget.fillFieldMap()

	return _reviewFeedbackTarget
}

type reviewFeedbackTarget struct {
	reviewFeedbackTargetDo reviewFeedbackTargetDo

	ALL        field.Asterisk
	ID         field.Int64
	FeedbackID field.Int64
	TargetType field.String
	TargetRef  field.String

	fieldMap map[string]field.Expr
}

func (r reviewFeedbackTarget) Table(newTableName string) *reviewFeedbackTarget {
	r.reviewFeedbackTargetDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewFeedbackTarget) As(alias string) *reviewFeedbackTarget {
	r.reviewFeedbackTargetDo.DO = *(r.reviewFeedbackTargetDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewFeedbackTarget) updateTableName(table string) *reviewFeedbackTarget {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.FeedbackID = field.NewInt64(table, "feedback_id")
	r.TargetType = field.NewString(table, "target_type")
	r.TargetRef = field.NewString(table, "target_ref")

	r.fillFieldMap()

	return r
}

func (r *reviewFeedbackTarget) WithContext(ctx context.Context) IReviewFeedbackTargetDo {
	return r.reviewFeedbackTargetDo.WithContext(ctx)
}

func (r reviewFeedbackTarget) TableName() string { return r.reviewFeedbackTargetDo.TableName() }

func (r reviewFeedbackTarget) Alias() string { return r.reviewFeedbackTargetDo.Alias() }

func (r reviewFeedbackTarget) Columns(cols ...field.Expr) gen.Columns {
	return r.reviewFeedbackTargetDo.Columns(cols...)
}

func (r *reviewFeedbackTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewFeedbackTarget) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["feedback_id"] = r.FeedbackID
	r.fieldMap["target_type"] = r.TargetType
	r.fieldMap["target_ref"] = r.TargetRef
}

func (r reviewFeedbackTarget) clone(db *gorm.DB) reviewFeedbackTarget {
	r.reviewFeedbackTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reviewFeedbackTarget) replaceDB(db *gorm.DB) reviewFeedbackTarget {
	r.reviewFeedbackTargetDo.ReplaceDB(db)
	return r
}

type reviewFeedbackTargetDo struct{ gen.DO }

type IReviewFeedbackTargetDo interface {
	gen.SubQuery
	Debug() IReviewFeedbackTargetDo
	WithContext(ctx context.Context) IReviewFeedbackTargetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReviewFeedbackTargetDo
	WriteDB() IReviewFeedbackTargetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReviewFeedbackTargetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReviewFeedbackTargetDo
	Not(conds ...gen.Condition) IReviewFeedbackTargetDo
	Or(conds ...gen.Condition) IReviewFeedbackTargetDo
	Select(conds ...field.Expr) IReviewFeedbackTargetDo
	Where(conds ...gen.Condition) IReviewFeedbackTargetDo
	Order(conds ...field.Expr) IReviewFeedbackTargetDo
	Distinct(cols ...field.Expr) IReviewFeedbackTargetDo
	Omit(cols ...field.Expr) IReviewFeedbackTargetDo
	Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackTargetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackTargetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackTargetDo
	Group(cols ...field.Expr) IReviewFeedbackTargetDo
	Having(conds ...gen.Condition) IReviewFeedbackTargetDo
	Limit(limit int) IReviewFeedbackTargetDo
	Offset(offset int) IReviewFeedbackTargetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackTargetDo
	Unscoped() IReviewFeedbackTargetDo
	Create(values ...*entity.ReviewFeedbackTarget) error
	CreateInBatches(values []*entity.ReviewFeedbackTarget, batchSize int) error
	Save(values ...*entity.ReviewFeedbackTarget) error
	First() (*entity.ReviewFeedbackTarget, error)
	Take() (*entity.ReviewFeedbackTarget, error)
	Last() (*entity.ReviewFeedbackTarget, error)
	Find() ([]*entity.ReviewFeedbackTarget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedbackTarget, err error)
	FindInBatches(result *[]*entity.ReviewFeedbackTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ReviewFeedbackTarget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReviewFeedbackTargetDo
	Assign(attrs ...field.AssignExpr) IReviewFeedbackTargetDo
	Joins(fields ...field.RelationField) IReviewFeedbackTargetDo
	Preload(fields ...field.RelationField) IReviewFeedbackTargetDo
	FirstOrInit() (*entity.ReviewFeedbackTarget, error)
	FirstOrCreate() (*entity.ReviewFeedbackTarget, error)
	FindByPage(offset int, limit int) (result []*entity.ReviewFeedbackTarget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReviewFeedbackTargetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reviewFeedbackTargetDo) Debug() IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewFeedbackTargetDo) WithContext(ctx context.Context) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewFeedbackTargetDo) ReadDB() IReviewFeedbackTargetDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewFeedbackTargetDo) WriteDB() IReviewFeedbackTargetDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewFeedbackTargetDo) Session(config *gorm.Session) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewFeedbackTargetDo) Clauses(conds ...clause.Expression) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewFeedbackTargetDo) Returning(value interface{}, columns ...string) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewFeedbackTargetDo) Not(conds ...gen.Condition) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewFeedbackTargetDo) Or(conds ...gen.Condition) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewFeedbackTargetDo) Select(conds ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewFeedbackTargetDo) Where(conds ...gen.Condition) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewFeedbackTargetDo) Order(conds ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewFeedbackTargetDo) Distinct(cols ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewFeedbackTargetDo) Omit(cols ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewFeedbackTargetDo) Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewFeedbackTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewFeedbackTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewFeedbackTargetDo) Group(cols ...field.Expr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewFeedbackTargetDo) Having(conds ...gen.Condition) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewFeedbackTargetDo) Limit(limit int) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewFeedbackTargetDo) Offset(offset int) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewFeedbackTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewFeedbackTargetDo) Unscoped() IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewFeedbackTargetDo) Create(values ...*entity.ReviewFeedbackTarget) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewFeedbackTargetDo) CreateInBatches(values []*entity.ReviewFeedbackTarget, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewFeedbackTargetDo) Save(values ...*entity.ReviewFeedbackTarget) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewFeedbackTargetDo) First() (*entity.ReviewFeedbackTarget, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackTarget), nil
	}
}

func (r reviewFeedbackTargetDo) Take() (*entity.ReviewFeedbackTarget, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackTarget), nil
	}
}

func (r reviewFeedbackTargetDo) Last() (*entity.ReviewFeedbackTarget, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackTarget), nil
	}
}

func (r reviewFeedbackTargetDo) Find() ([]*entity.ReviewFeedbackTarget, error) {
	result, err := r.DO.Find()
	return result.([]*entity.ReviewFeedbackTarget), err
}

func (r reviewFeedbackTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedbackTarget, err error) {
	buf := make([]*entity.ReviewFeedbackTarget, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewFeedbackTargetDo) FindInBatches(result *[]*entity.ReviewFeedbackTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewFeedbackTargetDo) Attrs(attrs ...field.AssignExpr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewFeedbackTargetDo) Assign(attrs ...field.AssignExpr) IReviewFeedbackTargetDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewFeedbackTargetDo) Joins(fields ...field.RelationField) IReviewFeedbackTargetDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewFeedbackTargetDo) Preload(fields ...field.RelationField) IReviewFeedbackTargetDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewFeedbackTargetDo) FirstOrInit() (*entity.ReviewFeedbackTarget, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackTarget), nil
	}
}

func (r reviewFeedbackTargetDo) FirstOrCreate() (*entity.ReviewFeedbackTarget, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackTarget), nil
	}
}

func (r reviewFeedbackTargetDo) FindByPage(offset int, limit int) (result []*entity.ReviewFeedbackTarget, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewFeedbackTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewFeedbackTargetDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewFeedbackTargetDo) Delete(models ...*entity.ReviewFeedbackTarget) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewFeedbackTargetDo) withDO(do gen.Dao) *reviewFeedbackTargetDo {
	r.DO = *do.(*gen.DO)
	return r
}
