// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newReviewFeedbackAction(db *gorm.DB, opts ...gen.DOOption) reviewFeedbackAction {
	_reviewFeedbackAction := reviewFeedbackAction{}

	_reviewFeedbackAction.reviewFeedbackActionDo.UseDB(db, opts...)
	_reviewFeedbackAction.reviewFeedbackActionDo.UseModel(&entity.ReviewFeedbackAction{})

	tableName := _reviewFeedbackAction.reviewFeedbackActionDo.TableName()
	_reviewFeedbackAction.ALL = field.NewAsterisk(tableName)
	_reviewFeedbackAction.ID = field.NewInt64(tableName, "id")
	_reviewFeedbackAction.FeedbackID = field.NewInt64(tableName, "feedback_id")
	_reviewFeedbackAction.ActionType = field.NewString(tableName, "action_type")
	_reviewFeedbackAction.Resolution = field.NewString(tableName, "resolution")
	_reviewFeedbackAction.ActedBy = field.NewInt64(tableName, "acted_by")
	_reviewFeedbackAction.CreatedAt = field.NewTime(tableName, "created_at")

	_reviewFeedbackAction.fillFieldMap()

	return _reviewFeedbackAction
}

type reviewFeedbackAction struct {
	reviewFeedbackActionDo reviewFeedbackActionDo

	ALL        field.Asterisk
	ID         field.Int64
	FeedbackID field.Int64
	ActionType field.String
	Resolution field.String
	ActedBy    field.Int64
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (r reviewFeedbackAction) Table(newTableName string) *reviewFeedbackAction {
	r.reviewFeedbackActionDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewFeedbackAction) As(alias string) *reviewFeedbackAction {
	r.reviewFeedbackActionDo.DO = *(r.reviewFeedbackActionDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewFeedbackAction) updateTableName(table string) *reviewFeedbackAction {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.FeedbackID = field.NewInt64(table, "feedback_id")
	r.ActionType = field.NewString(table, "action_type")
	r.Resolution = field.NewString(table, "resolution")
	r.ActedBy = field.NewInt64(table, "acted_by")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *reviewFeedbackAction) WithContext(ctx context.Context) IReviewFeedbackActionDo {
	return r.reviewFeedbackActionDo.WithContext(ctx)
}

func (r reviewFeedbackAction) TableName() string { return r.reviewFeedbackActionDo.TableName() }

func (r reviewFeedbackAction) Alias() string { return r.reviewFeedbackActionDo.Alias() }

func (r reviewFeedbackAction) Columns(cols ...field.Expr) gen.Columns {
	return r.reviewFeedbackActionDo.Columns(cols...)
}

func (r *reviewFeedbackAction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewFeedbackAction) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["feedback_id"] = r.FeedbackID
	r.fieldMap["action_type"] = r.ActionType
	r.fieldMap["resolution"] = r.Resolution
	r.fieldMap["acted_by"] = r.ActedBy
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r reviewFeedbackAction) clone(db *gorm.DB) reviewFeedbackAction {
	r.reviewFeedbackActionDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reviewFeedbackAction) replaceDB(db *gorm.DB) reviewFeedbackAction {
	r.reviewFeedbackActionDo.ReplaceDB(db)
	return r
}

type reviewFeedbackActionDo struct{ gen.DO }

type IReviewFeedbackActionDo interface {
	gen.SubQuery
	Debug() IReviewFeedbackActionDo
	WithContext(ctx context.Context) IReviewFeedbackActionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReviewFeedbackActionDo
	WriteDB() IReviewFeedbackActionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReviewFeedbackActionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReviewFeedbackActionDo
	Not(conds ...gen.Condition) IReviewFeedbackActionDo
	Or(conds ...gen.Condition) IReviewFeedbackActionDo
	Select(conds ...field.Expr) IReviewFeedbackActionDo
	Where(conds ...gen.Condition) IReviewFeedbackActionDo
	Order(conds ...field.Expr) IReviewFeedbackActionDo
	Distinct(cols ...field.Expr) IReviewFeedbackActionDo
	Omit(cols ...field.Expr) IReviewFeedbackActionDo
	Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackActionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackActionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackActionDo
	Group(cols ...field.Expr) IReviewFeedbackActionDo
	Having(conds ...gen.Condition) IReviewFeedbackActionDo
	Limit(limit int) IReviewFeedbackActionDo
	Offset(offset int) IReviewFeedbackActionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackActionDo
	Unscoped() IReviewFeedbackActionDo
	Create(values ...*entity.ReviewFeedbackAction) error
	CreateInBatches(values []*entity.ReviewFeedbackAction, batchSize int) error
	Save(values ...*entity.ReviewFeedbackAction) error
	First() (*entity.ReviewFeedbackAction, error)
	Take() (*entity.ReviewFeedbackAction, error)
	Last() (*entity.ReviewFeedbackAction, error)
	Find() ([]*entity.ReviewFeedbackAction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedbackAction, err error)
	FindInBatches(result *[]*entity.ReviewFeedbackAction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ReviewFeedbackAction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReviewFeedbackActionDo
	Assign(attrs ...field.AssignExpr) IReviewFeedbackActionDo
	Joins(fields ...field.RelationField) IReviewFeedbackActionDo
	Preload(fields ...field.RelationField) IReviewFeedbackActionDo
	FirstOrInit() (*entity.ReviewFeedbackAction, error)
	FirstOrCreate() (*entity.ReviewFeedbackAction, error)
	FindByPage(offset int, limit int) (result []*entity.ReviewFeedbackAction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReviewFeedbackActionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reviewFeedbackActionDo) Debug() IReviewFeedbackActionDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewFeedbackActionDo) WithContext(ctx context.Context) IReviewFeedbackActionDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewFeedbackActionDo) ReadDB() IReviewFeedbackActionDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewFeedbackActionDo) WriteDB() IReviewFeedbackActionDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewFeedbackActionDo) Session(config *gorm.Session) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewFeedbackActionDo) Clauses(conds ...clause.Expression) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewFeedbackActionDo) Returning(value interface{}, columns ...string) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewFeedbackActionDo) Not(conds ...gen.Condition) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewFeedbackActionDo) Or(conds ...gen.Condition) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewFeedbackActionDo) Select(conds ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewFeedbackActionDo) Where(conds ...gen.Condition) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewFeedbackActionDo) Order(conds ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewFeedbackActionDo) Distinct(cols ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewFeedbackActionDo) Omit(cols ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewFeedbackActionDo) Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewFeedbackActionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewFeedbackActionDo) RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewFeedbackActionDo) Group(cols ...field.Expr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewFeedbackActionDo) Having(conds ...gen.Condition) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewFeedbackActionDo) Limit(limit int) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewFeedbackActionDo) Offset(offset int) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewFeedbackActionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewFeedbackActionDo) Unscoped() IReviewFeedbackActionDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewFeedbackActionDo) Create(values ...*entity.ReviewFeedbackAction) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewFeedbackActionDo) CreateInBatches(values []*entity.ReviewFeedbackAction, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewFeedbackActionDo) Save(values ...*entity.ReviewFeedbackAction) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewFeedbackActionDo) First() (*entity.ReviewFeedbackAction, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackAction), nil
	}
}

func (r reviewFeedbackActionDo) Take() (*entity.ReviewFeedbackAction, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackAction), nil
	}
}

func (r reviewFeedbackActionDo) Last() (*entity.ReviewFeedbackAction, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackAction), nil
	}
}

func (r reviewFeedbackActionDo) Find() ([]*entity.ReviewFeedbackAction, error) {
	result, err := r.DO.Find()
	return result.([]*entity.ReviewFeedbackAction), err
}

func (r reviewFeedbackActionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedbackAction, err error) {
	buf := make([]*entity.ReviewFeedbackAction, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewFeedbackActionDo) FindInBatches(result *[]*entity.ReviewFeedbackAction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewFeedbackActionDo) Attrs(attrs ...field.AssignExpr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewFeedbackActionDo) Assign(attrs ...field.AssignExpr) IReviewFeedbackActionDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewFeedbackActionDo) Joins(fields ...field.RelationField) IReviewFeedbackActionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewFeedbackActionDo) Preload(fields ...field.RelationField) IReviewFeedbackActionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewFeedbackActionDo) FirstOrInit() (*entity.ReviewFeedbackAction, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackAction), nil
	}
}

func (r reviewFeedbackActionDo) FirstOrCreate() (*entity.ReviewFeedbackAction, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackAction), nil
	}
}

func (r reviewFeedbackActionDo) FindByPage(offset int, limit int) (result []*entity.ReviewFeedbackAction, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewFeedbackActionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewFeedbackActionDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewFeedbackActionDo) Delete(models ...*entity.ReviewFeedbackAction) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewFeedbackActionDo) withDO(do gen.Dao) *reviewFeedbackActionDo {
	r.DO = *do.(*gen.DO)
	return r
}
