// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newReviewJob(db *gorm.DB, opts ...gen.DOOption) reviewJob {
	_reviewJob := reviewJob{}

	_reviewJob.reviewJobDo.UseDB(db, opts...)
	_reviewJob.reviewJobDo.UseModel(&entity.ReviewJob{})

	tableName := _reviewJob.reviewJobDo.TableName()
	_reviewJob.ALL = field.NewAsterisk(tableName)
	_reviewJob.ID = field.NewInt64(tableName, "id")
	_reviewJob.VariantID = field.NewInt64(tableName, "variant_id")
	_reviewJob.RequestedBy = field.NewInt64(tableName, "requested_by")
	_reviewJob.Status = field.NewString(tableName, "status")
	_reviewJob.ErrorMessage = field.NewString(tableName, "error_message")
	_reviewJob.StartedAt = field.NewTime(tableName, "started_at")
	_reviewJob.FinishedAt = field.NewTime(tableName, "finished_at")
	_reviewJob.CreatedAt = field.NewTime(tableName, "created_at")

	_reviewJob.fillFieldMap()

	return _reviewJob
}

type reviewJob struct {
	reviewJobDo reviewJobDo

	ALL          field.Asterisk
	ID           field.Int64
	VariantID    field.Int64
	RequestedBy  field.Int64
	Status       field.String
	ErrorMessage field.String
	StartedAt    field.Time
	FinishedAt   field.Time
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (r reviewJob) Table(newTableName string) *reviewJob {
	r.reviewJobDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewJob) As(alias string) *reviewJob {
	r.reviewJobDo.DO = *(r.reviewJobDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewJob) updateTableName(table string) *reviewJob {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.VariantID = field.NewInt64(table, "variant_id")
	r.RequestedBy = field.NewInt64(table, "requested_by")
	r.Status = field.NewString(table, "status")
	r.ErrorMessage = field.NewString(table, "error_message")
	r.StartedAt = field.NewTime(table, "started_at")
	r.FinishedAt = field.NewTime(table, "finished_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *reviewJob) WithContext(ctx context.Context) IReviewJobDo {
	return r.reviewJobDo.WithContext(ctx)
}

func (r reviewJob) TableName() string { return r.reviewJobDo.TableName() }

func (r reviewJob) Alias() string { return r.reviewJobDo.Alias() }

func (r reviewJob) Columns(cols ...field.Expr) gen.Columns { return r.reviewJobDo.Columns(cols...) }

func (r *reviewJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewJob) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["variant_id"] = r.VariantID
	r.fieldMap["requested_by"] = r.RequestedBy
	r.fieldMap["status"] = r.Status
	r.fieldMap["error_message"] = r.ErrorMessage
	r.fieldMap["started_at"] = r.StartedAt
	r.fieldMap["finished_at"] = r.FinishedAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r reviewJob) clone(db *gorm.DB) reviewJob {
	r.reviewJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reviewJob) replaceDB(db *gorm.DB) reviewJob {
	r.reviewJobDo.ReplaceDB(db)
	return r
}

type reviewJobDo struct{ gen.DO }

type IReviewJobDo interface {
	gen.SubQuery
	Debug() IReviewJobDo
	WithContext(ctx context.Context) IReviewJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReviewJobDo
	WriteDB() IReviewJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReviewJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReviewJobDo
	Not(conds ...gen.Condition) IReviewJobDo
	Or(conds ...gen.Condition) IReviewJobDo
	Select(conds ...field.Expr) IReviewJobDo
	Where(conds ...gen.Condition) IReviewJobDo
	Order(conds ...field.Expr) IReviewJobDo
	Distinct(cols ...field.Expr) IReviewJobDo
	Omit(cols ...field.Expr) IReviewJobDo
	Join(table schema.Tabler, on ...field.Expr) IReviewJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReviewJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReviewJobDo
	Group(cols ...field.Expr) IReviewJobDo
	Having(conds ...gen.Condition) IReviewJobDo
	Limit(limit int) IReviewJobDo
	Offset(offset int) IReviewJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewJobDo
	Unscoped() IReviewJobDo
	Create(values ...*entity.ReviewJob) error
	CreateInBatches(values []*entity.ReviewJob, batchSize int) error
	Save(values ...*entity.ReviewJob) error
	First() (*entity.ReviewJob, error)
	Take() (*entity.ReviewJob, error)
	Last() (*entity.ReviewJob, error)
	Find() ([]*entity.ReviewJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewJob, err error)
	FindInBatches(result *[]*entity.ReviewJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ReviewJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReviewJobDo
	Assign(attrs ...field.AssignExpr) IReviewJobDo
	Joins(fields ...field.RelationField) IReviewJobDo
	Preload(fields ...field.RelationField) IReviewJobDo
	FirstOrInit() (*entity.ReviewJob, error)
	FirstOrCreate() (*entity.ReviewJob, error)
	FindByPage(offset int, limit int) (result []*entity.ReviewJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReviewJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reviewJobDo) Debug() IReviewJobDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewJobDo) WithContext(ctx context.Context) IReviewJobDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewJobDo) ReadDB() IReviewJobDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewJobDo) WriteDB() IReviewJobDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewJobDo) Session(config *gorm.Session) IReviewJobDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewJobDo) Clauses(conds ...clause.Expression) IReviewJobDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewJobDo) Returning(value interface{}, columns ...string) IReviewJobDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewJobDo) Not(conds ...gen.Condition) IReviewJobDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewJobDo) Or(conds ...gen.Condition) IReviewJobDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewJobDo) Select(conds ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewJobDo) Where(conds ...gen.Condition) IReviewJobDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewJobDo) Order(conds ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewJobDo) Distinct(cols ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewJobDo) Omit(cols ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewJobDo) Join(table schema.Tabler, on ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewJobDo) Group(cols ...field.Expr) IReviewJobDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewJobDo) Having(conds ...gen.Condition) IReviewJobDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewJobDo) Limit(limit int) IReviewJobDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewJobDo) Offset(offset int) IReviewJobDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewJobDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewJobDo) Unscoped() IReviewJobDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewJobDo) Create(values ...*entity.ReviewJob) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewJobDo) CreateInBatches(values []*entity.ReviewJob, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewJobDo) Save(values ...*entity.ReviewJob) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewJobDo) First() (*entity.ReviewJob, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewJob), nil
	}
}

func (r reviewJobDo) Take() (*entity.ReviewJob, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewJob), nil
	}
}

func (r reviewJobDo) Last() (*entity.ReviewJob, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewJob), nil
	}
}

func (r reviewJobDo) Find() ([]*entity.ReviewJob, error) {
	result, err := r.DO.Find()
	return result.([]*entity.ReviewJob), err
}

func (r reviewJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewJob, err error) {
	buf := make([]*entity.ReviewJob, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewJobDo) FindInBatches(result *[]*entity.ReviewJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewJobDo) Attrs(attrs ...field.AssignExpr) IReviewJobDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewJobDo) Assign(attrs ...field.AssignExpr) IReviewJobDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewJobDo) Joins(fields ...field.RelationField) IReviewJobDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewJobDo) Preload(fields ...field.RelationField) IReviewJobDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewJobDo) FirstOrInit() (*entity.ReviewJob, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewJob), nil
	}
}

func (r reviewJobDo) FirstOrCreate() (*entity.ReviewJob, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewJob), nil
	}
}

func (r reviewJobDo) FindByPage(offset int, limit int) (result []*entity.ReviewJob, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewJobDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewJobDo) Delete(models ...*entity.ReviewJob) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewJobDo) withDO(do gen.Dao) *reviewJobDo {
	r.DO = *do.(*gen.DO)
	return r
}
