// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newReviewFeedback(db *gorm.DB, opts ...gen.DOOption) reviewFeedback {
	_reviewFeedback := reviewFeedback{}

	_reviewFeedback.reviewFeedbackDo.UseDB(db, opts...)
	_reviewFeedback.reviewFeedbackDo.UseModel(&entity.ReviewFeedback{})

	tableName := _reviewFeedback.reviewFeedbackDo.TableName()
	_reviewFeedback.ALL = field.NewAsterisk(tableName)
	_reviewFeedback.ID = field.NewInt64(tableName, "id")
	_reviewFeedback.ReviewJobID = field.NewInt64(tableName, "review_job_id")
	_reviewFeedback.VariantID = field.NewInt64(tableName, "variant_id")
	_reviewFeedback.FeedbackType = field.NewString(tableName, "feedback_type")
	_reviewFeedback.Severity = field.NewString(tableName, "severity")
	_reviewFeedback.Title = field.NewString(tableName, "title")
	_reviewFeedback.Description = field.NewString(tableName, "description")
	_reviewFeedback.Suggestion = field.NewString(tableName, "suggestion")
	_reviewFeedback.AIRecommendation = field.NewString(tableName, "ai_recommendation")
	_reviewFeedback.Resolution = field.NewString(tableName, "resolution")
	_reviewFeedback.Status = field.NewString(tableName, "status")
	_reviewFeedback.DisplayOrder = field.NewInt32(tableName, "display_order")
	_reviewFeedback.CreatedAt = field.NewTime(tableName, "created_at")

	_reviewFeedback.fillFieldMap()

	return _reviewFeedback
}

type reviewFeedback struct {
	reviewFeedbackDo reviewFeedbackDo

	ALL              field.Asterisk
	ID               field.Int64
	ReviewJobID      field.Int64
	VariantID        field.Int64
	FeedbackType     field.String
	Severity         field.String
	Title            field.String
	Description      field.String
	Suggestion       field.String
	AIRecommendation field.String
	Resolution       field.String
	Status           field.String
	DisplayOrder     field.Int32
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (r reviewFeedback) Table(newTableName string) *reviewFeedback {
	r.reviewFeedbackDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewFeedback) As(alias string) *reviewFeedback {
	r.reviewFeedbackDo.DO = *(r.reviewFeedbackDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewFeedback) updateTableName(table string) *reviewFeedback {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.ReviewJobID = field.NewInt64(table, "review_job_id")
	r.VariantID = field.NewInt64(table, "variant_id")
	r.FeedbackType = field.NewString(table, "feedback_type")
	r.Severity = field.NewString(table, "severity")
	r.Title = field.NewString(table, "title")
	r.Description = field.NewString(table, "description")
	r.Suggestion = field.NewString(table, "suggestion")
	r.AIRecommendation = field.NewString(table, "ai_recommendation")
	r.Resolution = field.NewString(table, "resolution")
	r.Status = field.NewString(table, "status")
	r.DisplayOrder = field.NewInt32(table, "display_order")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *reviewFeedback) WithContext(ctx context.Context) IReviewFeedbackDo {
	return r.reviewFeedbackDo.WithContext(ctx)
}

func (r reviewFeedback) TableName() string { return r.reviewFeedbackDo.TableName() }

func (r reviewFeedback) Alias() string { return r.reviewFeedbackDo.Alias() }

func (r reviewFeedback) Columns(cols ...field.Expr) gen.Columns {
	return r.reviewFeedbackDo.Columns(cols...)
}

func (r *reviewFeedback) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewFeedback) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["review_job_id"] = r.ReviewJobID
	r.fieldMap["variant_id"] = r.VariantID
	r.fieldMap["feedback_type"] = r.FeedbackType
	r.fieldMap["severity"] = r.Severity
	r.fieldMap["title"] = r.Title
	r.fieldMap["description"] = r.Description
	r.fieldMap["suggestion"] = r.Suggestion
	r.fieldMap["ai_recommendation"] = r.AIRecommendation
	r.fieldMap["resolution"] = r.Resolution
	r.fieldMap["status"] = r.Status
	r.fieldMap["display_order"] = r.DisplayOrder
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r reviewFeedback) clone(db *gorm.DB) reviewFeedback {
	r.reviewFeedbackDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reviewFeedback) replaceDB(db *gorm.DB) reviewFeedback {
	r.reviewFeedbackDo.ReplaceDB(db)
	return r
}

type reviewFeedbackDo struct{ gen.DO }

type IReviewFeedbackDo interface {
	gen.SubQuery
	Debug() IReviewFeedbackDo
	WithContext(ctx context.Context) IReviewFeedbackDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReviewFeedbackDo
	WriteDB() IReviewFeedbackDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReviewFeedbackDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReviewFeedbackDo
	Not(conds ...gen.Condition) IReviewFeedbackDo
	Or(conds ...gen.Condition) IReviewFeedbackDo
	Select(conds ...field.Expr) IReviewFeedbackDo
	Where(conds ...gen.Condition) IReviewFeedbackDo
	Order(conds ...field.Expr) IReviewFeedbackDo
	Distinct(cols ...field.Expr) IReviewFeedbackDo
	Omit(cols ...field.Expr) IReviewFeedbackDo
	Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackDo
	Group(cols ...field.Expr) IReviewFeedbackDo
	Having(conds ...gen.Condition) IReviewFeedbackDo
	Limit(limit int) IReviewFeedbackDo
	Offset(offset int) IReviewFeedbackDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackDo
	Unscoped() IReviewFeedbackDo
	Create(values ...*entity.ReviewFeedback) error
	CreateInBatches(values []*entity.ReviewFeedback, batchSize int) error
	Save(values ...*entity.ReviewFeedback) error
	First() (*entity.ReviewFeedback, error)
	Take() (*entity.ReviewFeedback, error)
	Last() (*entity.ReviewFeedback, error)
	Find() ([]*entity.ReviewFeedback, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedback, err error)
	FindInBatches(result *[]*entity.ReviewFeedback, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ReviewFeedback) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReviewFeedbackDo
	Assign(attrs ...field.AssignExpr) IReviewFeedbackDo
	Joins(fields ...field.RelationField) IReviewFeedbackDo
	Preload(fields ...field.RelationField) IReviewFeedbackDo
	FirstOrInit() (*entity.ReviewFeedback, error)
	FirstOrCreate() (*entity.ReviewFeedback, error)
	FindByPage(offset int, limit int) (result []*entity.ReviewFeedback, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReviewFeedbackDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reviewFeedbackDo) Debug() IReviewFeedbackDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewFeedbackDo) WithContext(ctx context.Context) IReviewFeedbackDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewFeedbackDo) ReadDB() IReviewFeedbackDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewFeedbackDo) WriteDB() IReviewFeedbackDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewFeedbackDo) Session(config *gorm.Session) IReviewFeedbackDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewFeedbackDo) Clauses(conds ...clause.Expression) IReviewFeedbackDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewFeedbackDo) Returning(value interface{}, columns ...string) IReviewFeedbackDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewFeedbackDo) Not(conds ...gen.Condition) IReviewFeedbackDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewFeedbackDo) Or(conds ...gen.Condition) IReviewFeedbackDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewFeedbackDo) Select(conds ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewFeedbackDo) Where(conds ...gen.Condition) IReviewFeedbackDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewFeedbackDo) Order(conds ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewFeedbackDo) Distinct(cols ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewFeedbackDo) Omit(cols ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewFeedbackDo) Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewFeedbackDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewFeedbackDo) RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewFeedbackDo) Group(cols ...field.Expr) IReviewFeedbackDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewFeedbackDo) Having(conds ...gen.Condition) IReviewFeedbackDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewFeedbackDo) Limit(limit int) IReviewFeedbackDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewFeedbackDo) Offset(offset int) IReviewFeedbackDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewFeedbackDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewFeedbackDo) Unscoped() IReviewFeedbackDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewFeedbackDo) Create(values ...*entity.ReviewFeedback) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewFeedbackDo) CreateInBatches(values []*entity.ReviewFeedback, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewFeedbackDo) Save(values ...*entity.ReviewFeedback) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewFeedbackDo) First() (*entity.ReviewFeedback, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedback), nil
	}
}

func (r reviewFeedbackDo) Take() (*entity.ReviewFeedback, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedback), nil
	}
}

func (r reviewFeedbackDo) Last() (*entity.ReviewFeedback, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedback), nil
	}
}

func (r reviewFeedbackDo) Find() ([]*entity.ReviewFeedback, error) {
	result, err := r.DO.Find()
	return result.([]*entity.ReviewFeedback), err
}

func (r reviewFeedbackDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedback, err error) {
	buf := make([]*entity.ReviewFeedback, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewFeedbackDo) FindInBatches(result *[]*entity.ReviewFeedback, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewFeedbackDo) Attrs(attrs ...field.AssignExpr) IReviewFeedbackDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewFeedbackDo) Assign(attrs ...field.AssignExpr) IReviewFeedbackDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewFeedbackDo) Joins(fields ...field.RelationField) IReviewFeedbackDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewFeedbackDo) Preload(fields ...field.RelationField) IReviewFeedbackDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewFeedbackDo) FirstOrInit() (*entity.ReviewFeedback, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedback), nil
	}
}

func (r reviewFeedbackDo) FirstOrCreate() (*entity.ReviewFeedback, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedback), nil
	}
}

func (r reviewFeedbackDo) FindByPage(offset int, limit int) (result []*entity.ReviewFeedback, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewFeedbackDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewFeedbackDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewFeedbackDo) Delete(models ...*entity.ReviewFeedback) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewFeedbackDo) withDO(do gen.Dao) *reviewFeedbackDo {
	r.DO = *do.(*gen.DO)
	return r
}
