// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newReviewFeedbackChat(db *gorm.DB, opts ...gen.DOOption) reviewFeedbackChat {
	_reviewFeedbackChat := reviewFeedbackChat{}

	_reviewFeedbackChat.reviewFeedbackChatDo.UseDB(db, opts...)
	_reviewFeedbackChat.reviewFeedbackChatDo.UseModel(&entity.ReviewFeedbackChat{})

	tableName := _reviewFeedbackChat.reviewFeedbackChatDo.TableName()
	_reviewFeedbackChat.ALL = field.NewAsterisk(tableName)
	_reviewFeedbackChat.ID = field.NewInt64(tableName, "id")
	_reviewFeedbackChat.FeedbackID = field.NewInt64(tableName, "feedback_id")
	_reviewFeedbackChat.Role = field.NewString(tableName, "role")
	_reviewFeedbackChat.Content = field.NewString(tableName, "content")
	_reviewFeedbackChat.CreatedBy = field.NewInt64(tableName, "created_by")
	_reviewFeedbackChat.CreatedAt = field.NewTime(tableName, "created_at")

	_reviewFeedbackChat.fillFieldMap()

	return _reviewFeedbackChat
}

type reviewFeedbackChat struct {
	reviewFeedbackChatDo reviewFeedbackChatDo

	ALL        field.Asterisk
	ID         field.Int64
	FeedbackID field.Int64
	Role       field.String
	Content    field.String
	CreatedBy  field.Int64
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (r reviewFeedbackChat) Table(newTableName string) *reviewFeedbackChat {
	r.reviewFeedbackChatDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewFeedbackChat) As(alias string) *reviewFeedbackChat {
	r.reviewFeedbackChatDo.DO = *(r.reviewFeedbackChatDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewFeedbackChat) updateTableName(table string) *reviewFeedbackChat {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.FeedbackID = field.NewInt64(table, "feedback_id")
	r.Role = field.NewString(table, "role")
	r.Content = field.NewString(table, "content")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *reviewFeedbackChat) WithContext(ctx context.Context) IReviewFeedbackChatDo {
	return r.reviewFeedbackChatDo.WithContext(ctx)
}

func (r reviewFeedbackChat) TableName() string { return r.reviewFeedbackChatDo.TableName() }

func (r reviewFeedbackChat) Alias() string { return r.reviewFeedbackChatDo.Alias() }

func (r reviewFeedbackChat) Columns(cols ...field.Expr) gen.Columns {
	return r.reviewFeedbackChatDo.Columns(cols...)
}

func (r *reviewFeedbackChat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewFeedbackChat) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["feedback_id"] = r.FeedbackID
	r.fieldMap["role"] = r.Role
	r.fieldMap["content"] = r.Content
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r reviewFeedbackChat) clone(db *gorm.DB) reviewFeedbackChat {
	r.reviewFeedbackChatDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reviewFeedbackChat) replaceDB(db *gorm.DB) reviewFeedbackChat {
	r.reviewFeedbackChatDo.ReplaceDB(db)
	return r
}

type reviewFeedbackChatDo struct{ gen.DO }

type IReviewFeedbackChatDo interface {
	gen.SubQuery
	Debug() IReviewFeedbackChatDo
	WithContext(ctx context.Context) IReviewFeedbackChatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReviewFeedbackChatDo
	WriteDB() IReviewFeedbackChatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReviewFeedbackChatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReviewFeedbackChatDo
	Not(conds ...gen.Condition) IReviewFeedbackChatDo
	Or(conds ...gen.Condition) IReviewFeedbackChatDo
	Select(conds ...field.Expr) IReviewFeedbackChatDo
	Where(conds ...gen.Condition) IReviewFeedbackChatDo
	Order(conds ...field.Expr) IReviewFeedbackChatDo
	Distinct(cols ...field.Expr) IReviewFeedbackChatDo
	Omit(cols ...field.Expr) IReviewFeedbackChatDo
	Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackChatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackChatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackChatDo
	Group(cols ...field.Expr) IReviewFeedbackChatDo
	Having(conds ...gen.Condition) IReviewFeedbackChatDo
	Limit(limit int) IReviewFeedbackChatDo
	Offset(offset int) IReviewFeedbackChatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackChatDo
	Unscoped() IReviewFeedbackChatDo
	Create(values ...*entity.ReviewFeedbackChat) error
	CreateInBatches(values []*entity.ReviewFeedbackChat, batchSize int) error
	Save(values ...*entity.ReviewFeedbackChat) error
	First() (*entity.ReviewFeedbackChat, error)
	Take() (*entity.ReviewFeedbackChat, error)
	Last() (*entity.ReviewFeedbackChat, error)
	Find() ([]*entity.ReviewFeedbackChat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedbackChat, err error)
	FindInBatches(result *[]*entity.ReviewFeedbackChat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ReviewFeedbackChat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReviewFeedbackChatDo
	Assign(attrs ...field.AssignExpr) IReviewFeedbackChatDo
	Joins(fields ...field.RelationField) IReviewFeedbackChatDo
	Preload(fields ...field.RelationField) IReviewFeedbackChatDo
	FirstOrInit() (*entity.ReviewFeedbackChat, error)
	FirstOrCreate() (*entity.ReviewFeedbackChat, error)
	FindByPage(offset int, limit int) (result []*entity.ReviewFeedbackChat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReviewFeedbackChatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reviewFeedbackChatDo) Debug() IReviewFeedbackChatDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewFeedbackChatDo) WithContext(ctx context.Context) IReviewFeedbackChatDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewFeedbackChatDo) ReadDB() IReviewFeedbackChatDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewFeedbackChatDo) WriteDB() IReviewFeedbackChatDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewFeedbackChatDo) Session(config *gorm.Session) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewFeedbackChatDo) Clauses(conds ...clause.Expression) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewFeedbackChatDo) Returning(value interface{}, columns ...string) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewFeedbackChatDo) Not(conds ...gen.Condition) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewFeedbackChatDo) Or(conds ...gen.Condition) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewFeedbackChatDo) Select(conds ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewFeedbackChatDo) Where(conds ...gen.Condition) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewFeedbackChatDo) Order(conds ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewFeedbackChatDo) Distinct(cols ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewFeedbackChatDo) Omit(cols ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewFeedbackChatDo) Join(table schema.Tabler, on ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewFeedbackChatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewFeedbackChatDo) RightJoin(table schema.Tabler, on ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewFeedbackChatDo) Group(cols ...field.Expr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewFeedbackChatDo) Having(conds ...gen.Condition) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewFeedbackChatDo) Limit(limit int) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewFeedbackChatDo) Offset(offset int) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewFeedbackChatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewFeedbackChatDo) Unscoped() IReviewFeedbackChatDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewFeedbackChatDo) Create(values ...*entity.ReviewFeedbackChat) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewFeedbackChatDo) CreateInBatches(values []*entity.ReviewFeedbackChat, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewFeedbackChatDo) Save(values ...*entity.ReviewFeedbackChat) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewFeedbackChatDo) First() (*entity.ReviewFeedbackChat, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackChat), nil
	}
}

func (r reviewFeedbackChatDo) Take() (*entity.ReviewFeedbackChat, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackChat), nil
	}
}

func (r reviewFeedbackChatDo) Last() (*entity.ReviewFeedbackChat, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackChat), nil
	}
}

func (r reviewFeedbackChatDo) Find() ([]*entity.ReviewFeedbackChat, error) {
	result, err := r.DO.Find()
	return result.([]*entity.ReviewFeedbackChat), err
}

func (r reviewFeedbackChatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ReviewFeedbackChat, err error) {
	buf := make([]*entity.ReviewFeedbackChat, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewFeedbackChatDo) FindInBatches(result *[]*entity.ReviewFeedbackChat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewFeedbackChatDo) Attrs(attrs ...field.AssignExpr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewFeedbackChatDo) Assign(attrs ...field.AssignExpr) IReviewFeedbackChatDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewFeedbackChatDo) Joins(fields ...field.RelationField) IReviewFeedbackChatDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewFeedbackChatDo) Preload(fields ...field.RelationField) IReviewFeedbackChatDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewFeedbackChatDo) FirstOrInit() (*entity.ReviewFeedbackChat, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackChat), nil
	}
}

func (r reviewFeedbackChatDo) FirstOrCreate() (*entity.ReviewFeedbackChat, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ReviewFeedbackChat), nil
	}
}

func (r reviewFeedbackChatDo) FindByPage(offset int, limit int) (result []*entity.ReviewFeedbackChat, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewFeedbackChatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewFeedbackChatDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewFeedbackChatDo) Delete(models ...*entity.ReviewFeedbackChat) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewFeedbackChatDo) withDO(do gen.Dao) *reviewFeedbackChatDo {
	r.DO = *do.(*gen.DO)
	return r
}
