// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newVariantFile(db *gorm.DB, opts ...gen.DOOption) variantFile {
	_variantFile := variantFile{}

	_variantFile.variantFileDo.UseDB(db, opts...)
	_variantFile.variantFileDo.UseModel(&entity.VariantFile{})

	tableName := _variantFile.variantFileDo.TableName()
	_variantFile.ALL = field.NewAsterisk(tableName)
	_variantFile.ID = field.NewInt64(tableName, "id")
	_variantFile.VariantID = field.NewInt64(tableName, "variant_id")
	_variantFile.Path = field.NewString(tableName, "path")
	_variantFile.Language = field.NewString(tableName, "language")
	_variantFile.PackageName = field.NewString(tableName, "package_name")
	_variantFile.Imports = field.NewField(tableName, "imports")
	_variantFile.NodeCount = field.NewInt32(tableName, "node_count")
	_variantFile.IsVisible = field.NewBool(tableName, "is_visible")
	_variantFile.DisplayOrder = field.NewInt32(tableName, "display_order")
	_variantFile.CreatedAt = field.NewTime(tableName, "created_at")
	_variantFile.UpdatedAt = field.NewTime(tableName, "updated_at")

	_variantFile.fillFieldMap()

	return _variantFile
}

type variantFile struct {
	variantFileDo variantFileDo

	ALL          field.Asterisk
	ID           field.Int64
	VariantID    field.Int64
	Path         field.String
	Language     field.String
	PackageName  field.String
	Imports      field.Field
	NodeCount    field.Int32
	IsVisible    field.Bool
	DisplayOrder field.Int32
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (v variantFile) Table(newTableName string) *variantFile {
	v.variantFileDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v variantFile) As(alias string) *variantFile {
	v.variantFileDo.DO = *(v.variantFileDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *variantFile) updateTableName(table string) *variantFile {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.VariantID = field.NewInt64(table, "variant_id")
	v.Path = field.NewString(table, "path")
	v.Language = field.NewString(table, "language")
	v.PackageName = field.NewString(table, "package_name")
	v.Imports = field.NewField(table, "imports")
	v.NodeCount = field.NewInt32(table, "node_count")
	v.IsVisible = field.NewBool(table, "is_visible")
	v.DisplayOrder = field.NewInt32(table, "display_order")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *variantFile) WithContext(ctx context.Context) IVariantFileDo {
	return v.variantFileDo.WithContext(ctx)
}

func (v variantFile) TableName() string { return v.variantFileDo.TableName() }

func (v variantFile) Alias() string { return v.variantFileDo.Alias() }

func (v variantFile) Columns(cols ...field.Expr) gen.Columns { return v.variantFileDo.Columns(cols...) }

func (v *variantFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *variantFile) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 11)
	v.fieldMap["id"] = v.ID
	v.fieldMap["variant_id"] = v.VariantID
	v.fieldMap["path"] = v.Path
	v.fieldMap["language"] = v.Language
	v.fieldMap["package_name"] = v.PackageName
	v.fieldMap["imports"] = v.Imports
	v.fieldMap["node_count"] = v.NodeCount
	v.fieldMap["is_visible"] = v.IsVisible
	v.fieldMap["display_order"] = v.DisplayOrder
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v variantFile) clone(db *gorm.DB) variantFile {
	v.variantFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v variantFile) replaceDB(db *gorm.DB) variantFile {
	v.variantFileDo.ReplaceDB(db)
	return v
}

type variantFileDo struct{ gen.DO }

type IVariantFileDo interface {
	gen.SubQuery
	Debug() IVariantFileDo
	WithContext(ctx context.Context) IVariantFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVariantFileDo
	WriteDB() IVariantFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVariantFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVariantFileDo
	Not(conds ...gen.Condition) IVariantFileDo
	Or(conds ...gen.Condition) IVariantFileDo
	Select(conds ...field.Expr) IVariantFileDo
	Where(conds ...gen.Condition) IVariantFileDo
	Order(conds ...field.Expr) IVariantFileDo
	Distinct(cols ...field.Expr) IVariantFileDo
	Omit(cols ...field.Expr) IVariantFileDo
	Join(table schema.Tabler, on ...field.Expr) IVariantFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVariantFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVariantFileDo
	Group(cols ...field.Expr) IVariantFileDo
	Having(conds ...gen.Condition) IVariantFileDo
	Limit(limit int) IVariantFileDo
	Offset(offset int) IVariantFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVariantFileDo
	Unscoped() IVariantFileDo
	Create(values ...*entity.VariantFile) error
	CreateInBatches(values []*entity.VariantFile, batchSize int) error
	Save(values ...*entity.VariantFile) error
	First() (*entity.VariantFile, error)
	Take() (*entity.VariantFile, error)
	Last() (*entity.VariantFile, error)
	Find() ([]*entity.VariantFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.VariantFile, err error)
	FindInBatches(result *[]*entity.VariantFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.VariantFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVariantFileDo
	Assign(attrs ...field.AssignExpr) IVariantFileDo
	Joins(fields ...field.RelationField) IVariantFileDo
	Preload(fields ...field.RelationField) IVariantFileDo
	FirstOrInit() (*entity.VariantFile, error)
	FirstOrCreate() (*entity.VariantFile, error)
	FindByPage(offset int, limit int) (result []*entity.VariantFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVariantFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v variantFileDo) Debug() IVariantFileDo {
	return v.withDO(v.DO.Debug())
}

func (v variantFileDo) WithContext(ctx context.Context) IVariantFileDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v variantFileDo) ReadDB() IVariantFileDo {
	return v.Clauses(dbresolver.Read)
}

func (v variantFileDo) WriteDB() IVariantFileDo {
	return v.Clauses(dbresolver.Write)
}

func (v variantFileDo) Session(config *gorm.Session) IVariantFileDo {
	return v.withDO(v.DO.Session(config))
}

func (v variantFileDo) Clauses(conds ...clause.Expression) IVariantFileDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v variantFileDo) Returning(value interface{}, columns ...string) IVariantFileDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v variantFileDo) Not(conds ...gen.Condition) IVariantFileDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v variantFileDo) Or(conds ...gen.Condition) IVariantFileDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v variantFileDo) Select(conds ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v variantFileDo) Where(conds ...gen.Condition) IVariantFileDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v variantFileDo) Order(conds ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v variantFileDo) Distinct(cols ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v variantFileDo) Omit(cols ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v variantFileDo) Join(table schema.Tabler, on ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v variantFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v variantFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v variantFileDo) Group(cols ...field.Expr) IVariantFileDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v variantFileDo) Having(conds ...gen.Condition) IVariantFileDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v variantFileDo) Limit(limit int) IVariantFileDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v variantFileDo) Offset(offset int) IVariantFileDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v variantFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVariantFileDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v variantFileDo) Unscoped() IVariantFileDo {
	return v.withDO(v.DO.Unscoped())
}

func (v variantFileDo) Create(values ...*entity.VariantFile) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v variantFileDo) CreateInBatches(values []*entity.VariantFile, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v variantFileDo) Save(values ...*entity.VariantFile) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v variantFileDo) First() (*entity.VariantFile, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantFile), nil
	}
}

func (v variantFileDo) Take() (*entity.VariantFile, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantFile), nil
	}
}

func (v variantFileDo) Last() (*entity.VariantFile, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantFile), nil
	}
}

func (v variantFileDo) Find() ([]*entity.VariantFile, error) {
	result, err := v.DO.Find()
	return result.([]*entity.VariantFile), err
}

func (v variantFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.VariantFile, err error) {
	buf := make([]*entity.VariantFile, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v variantFileDo) FindInBatches(result *[]*entity.VariantFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v variantFileDo) Attrs(attrs ...field.AssignExpr) IVariantFileDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v variantFileDo) Assign(attrs ...field.AssignExpr) IVariantFileDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v variantFileDo) Joins(fields ...field.RelationField) IVariantFileDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v variantFileDo) Preload(fields ...field.RelationField) IVariantFileDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v variantFileDo) FirstOrInit() (*entity.VariantFile, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantFile), nil
	}
}

func (v variantFileDo) FirstOrCreate() (*entity.VariantFile, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantFile), nil
	}
}

func (v variantFileDo) FindByPage(offset int, limit int) (result []*entity.VariantFile, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v variantFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v variantFileDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v variantFileDo) Delete(models ...*entity.VariantFile) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *variantFileDo) withDO(do gen.Dao) *variantFileDo {
	v.DO = *do.(*gen.DO)
	return v
}
