// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newVariantDesignGuide(db *gorm.DB, opts ...gen.DOOption) variantDesignGuide {
	_variantDesignGuide := variantDesignGuide{}

	_variantDesignGuide.variantDesignGuideDo.UseDB(db, opts...)
	_variantDesignGuide.variantDesignGuideDo.UseModel(&entity.VariantDesignGuide{})

	tableName := _variantDesignGuide.variantDesignGuideDo.TableName()
	_variantDesignGuide.ALL = field.NewAsterisk(tableName)
	_variantDesignGuide.ID = field.NewInt64(tableName, "id")
	_variantDesignGuide.VariantID = field.NewInt64(tableName, "variant_id")
	_variantDesignGuide.BaseDesignGuideID = field.NewInt64(tableName, "base_design_guide_id")
	_variantDesignGuide.Title = field.NewString(tableName, "title")
	_variantDesignGuide.Description = field.NewString(tableName, "description")
	_variantDesignGuide.Content = field.NewString(tableName, "content")
	_variantDesignGuide.Version = field.NewInt32(tableName, "version")
	_variantDesignGuide.CreatedBy = field.NewInt64(tableName, "created_by")
	_variantDesignGuide.CreatedAt = field.NewTime(tableName, "created_at")
	_variantDesignGuide.UpdatedAt = field.NewTime(tableName, "updated_at")

	_variantDesignGuide.fillFieldMap()

	return _variantDesignGuide
}

type variantDesignGuide struct {
	variantDesignGuideDo variantDesignGuideDo

	ALL               field.Asterisk
	ID                field.Int64
	VariantID         field.Int64
	BaseDesignGuideID field.Int64
	Title             field.String
	Description       field.String
	Content           field.String
	Version           field.Int32
	CreatedBy         field.Int64
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (v variantDesignGuide) Table(newTableName string) *variantDesignGuide {
	v.variantDesignGuideDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v variantDesignGuide) As(alias string) *variantDesignGuide {
	v.variantDesignGuideDo.DO = *(v.variantDesignGuideDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *variantDesignGuide) updateTableName(table string) *variantDesignGuide {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.VariantID = field.NewInt64(table, "variant_id")
	v.BaseDesignGuideID = field.NewInt64(table, "base_design_guide_id")
	v.Title = field.NewString(table, "title")
	v.Description = field.NewString(table, "description")
	v.Content = field.NewString(table, "content")
	v.Version = field.NewInt32(table, "version")
	v.CreatedBy = field.NewInt64(table, "created_by")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *variantDesignGuide) WithContext(ctx context.Context) IVariantDesignGuideDo {
	return v.variantDesignGuideDo.WithContext(ctx)
}

func (v variantDesignGuide) TableName() string { return v.variantDesignGuideDo.TableName() }

func (v variantDesignGuide) Alias() string { return v.variantDesignGuideDo.Alias() }

func (v variantDesignGuide) Columns(cols ...field.Expr) gen.Columns {
	return v.variantDesignGuideDo.Columns(cols...)
}

func (v *variantDesignGuide) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *variantDesignGuide) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 10)
	v.fieldMap["id"] = v.ID
	v.fieldMap["variant_id"] = v.VariantID
	v.fieldMap["base_design_guide_id"] = v.BaseDesignGuideID
	v.fieldMap["title"] = v.Title
	v.fieldMap["description"] = v.Description
	v.fieldMap["content"] = v.Content
	v.fieldMap["version"] = v.Version
	v.fieldMap["created_by"] = v.CreatedBy
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v variantDesignGuide) clone(db *gorm.DB) variantDesignGuide {
	v.variantDesignGuideDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v variantDesignGuide) replaceDB(db *gorm.DB) variantDesignGuide {
	v.variantDesignGuideDo.ReplaceDB(db)
	return v
}

type variantDesignGuideDo struct{ gen.DO }

type IVariantDesignGuideDo interface {
	gen.SubQuery
	Debug() IVariantDesignGuideDo
	WithContext(ctx context.Context) IVariantDesignGuideDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVariantDesignGuideDo
	WriteDB() IVariantDesignGuideDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVariantDesignGuideDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVariantDesignGuideDo
	Not(conds ...gen.Condition) IVariantDesignGuideDo
	Or(conds ...gen.Condition) IVariantDesignGuideDo
	Select(conds ...field.Expr) IVariantDesignGuideDo
	Where(conds ...gen.Condition) IVariantDesignGuideDo
	Order(conds ...field.Expr) IVariantDesignGuideDo
	Distinct(cols ...field.Expr) IVariantDesignGuideDo
	Omit(cols ...field.Expr) IVariantDesignGuideDo
	Join(table schema.Tabler, on ...field.Expr) IVariantDesignGuideDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVariantDesignGuideDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVariantDesignGuideDo
	Group(cols ...field.Expr) IVariantDesignGuideDo
	Having(conds ...gen.Condition) IVariantDesignGuideDo
	Limit(limit int) IVariantDesignGuideDo
	Offset(offset int) IVariantDesignGuideDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVariantDesignGuideDo
	Unscoped() IVariantDesignGuideDo
	Create(values ...*entity.VariantDesignGuide) error
	CreateInBatches(values []*entity.VariantDesignGuide, batchSize int) error
	Save(values ...*entity.VariantDesignGuide) error
	First() (*entity.VariantDesignGuide, error)
	Take() (*entity.VariantDesignGuide, error)
	Last() (*entity.VariantDesignGuide, error)
	Find() ([]*entity.VariantDesignGuide, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.VariantDesignGuide, err error)
	FindInBatches(result *[]*entity.VariantDesignGuide, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.VariantDesignGuide) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVariantDesignGuideDo
	Assign(attrs ...field.AssignExpr) IVariantDesignGuideDo
	Joins(fields ...field.RelationField) IVariantDesignGuideDo
	Preload(fields ...field.RelationField) IVariantDesignGuideDo
	FirstOrInit() (*entity.VariantDesignGuide, error)
	FirstOrCreate() (*entity.VariantDesignGuide, error)
	FindByPage(offset int, limit int) (result []*entity.VariantDesignGuide, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVariantDesignGuideDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v variantDesignGuideDo) Debug() IVariantDesignGuideDo {
	return v.withDO(v.DO.Debug())
}

func (v variantDesignGuideDo) WithContext(ctx context.Context) IVariantDesignGuideDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v variantDesignGuideDo) ReadDB() IVariantDesignGuideDo {
	return v.Clauses(dbresolver.Read)
}

func (v variantDesignGuideDo) WriteDB() IVariantDesignGuideDo {
	return v.Clauses(dbresolver.Write)
}

func (v variantDesignGuideDo) Session(config *gorm.Session) IVariantDesignGuideDo {
	return v.withDO(v.DO.Session(config))
}

func (v variantDesignGuideDo) Clauses(conds ...clause.Expression) IVariantDesignGuideDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v variantDesignGuideDo) Returning(value interface{}, columns ...string) IVariantDesignGuideDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v variantDesignGuideDo) Not(conds ...gen.Condition) IVariantDesignGuideDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v variantDesignGuideDo) Or(conds ...gen.Condition) IVariantDesignGuideDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v variantDesignGuideDo) Select(conds ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v variantDesignGuideDo) Where(conds ...gen.Condition) IVariantDesignGuideDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v variantDesignGuideDo) Order(conds ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v variantDesignGuideDo) Distinct(cols ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v variantDesignGuideDo) Omit(cols ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v variantDesignGuideDo) Join(table schema.Tabler, on ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v variantDesignGuideDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v variantDesignGuideDo) RightJoin(table schema.Tabler, on ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v variantDesignGuideDo) Group(cols ...field.Expr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v variantDesignGuideDo) Having(conds ...gen.Condition) IVariantDesignGuideDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v variantDesignGuideDo) Limit(limit int) IVariantDesignGuideDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v variantDesignGuideDo) Offset(offset int) IVariantDesignGuideDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v variantDesignGuideDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVariantDesignGuideDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v variantDesignGuideDo) Unscoped() IVariantDesignGuideDo {
	return v.withDO(v.DO.Unscoped())
}

func (v variantDesignGuideDo) Create(values ...*entity.VariantDesignGuide) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v variantDesignGuideDo) CreateInBatches(values []*entity.VariantDesignGuide, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v variantDesignGuideDo) Save(values ...*entity.VariantDesignGuide) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v variantDesignGuideDo) First() (*entity.VariantDesignGuide, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantDesignGuide), nil
	}
}

func (v variantDesignGuideDo) Take() (*entity.VariantDesignGuide, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantDesignGuide), nil
	}
}

func (v variantDesignGuideDo) Last() (*entity.VariantDesignGuide, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantDesignGuide), nil
	}
}

func (v variantDesignGuideDo) Find() ([]*entity.VariantDesignGuide, error) {
	result, err := v.DO.Find()
	return result.([]*entity.VariantDesignGuide), err
}

func (v variantDesignGuideDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.VariantDesignGuide, err error) {
	buf := make([]*entity.VariantDesignGuide, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v variantDesignGuideDo) FindInBatches(result *[]*entity.VariantDesignGuide, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v variantDesignGuideDo) Attrs(attrs ...field.AssignExpr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v variantDesignGuideDo) Assign(attrs ...field.AssignExpr) IVariantDesignGuideDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v variantDesignGuideDo) Joins(fields ...field.RelationField) IVariantDesignGuideDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v variantDesignGuideDo) Preload(fields ...field.RelationField) IVariantDesignGuideDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v variantDesignGuideDo) FirstOrInit() (*entity.VariantDesignGuide, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantDesignGuide), nil
	}
}

func (v variantDesignGuideDo) FirstOrCreate() (*entity.VariantDesignGuide, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.VariantDesignGuide), nil
	}
}

func (v variantDesignGuideDo) FindByPage(offset int, limit int) (result []*entity.VariantDesignGuide, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v variantDesignGuideDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v variantDesignGuideDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v variantDesignGuideDo) Delete(models ...*entity.VariantDesignGuide) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *variantDesignGuideDo) withDO(do gen.Dao) *variantDesignGuideDo {
	v.DO = *do.(*gen.DO)
	return v
}
