// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/GDGoC-Japan-Hackathon/affectify/backend/internal/repository/entity"
)

func newVariant(db *gorm.DB, opts ...gen.DOOption) variant {
	_variant := variant{}

	_variant.variantDo.UseDB(db, opts...)
	_variant.variantDo.UseModel(&entity.Variant{})

	tableName := _variant.variantDo.TableName()
	_variant.ALL = field.NewAsterisk(tableName)
	_variant.ID = field.NewInt64(tableName, "id")
	_variant.ProjectID = field.NewInt64(tableName, "project_id")
	_variant.Name = field.NewString(tableName, "name")
	_variant.Description = field.NewString(tableName, "description")
	_variant.IsMain = field.NewBool(tableName, "is_main")
	_variant.ForkedFromVariantID = field.NewInt64(tableName, "forked_from_variant_id")
	_variant.AnalysisScore = field.NewInt32(tableName, "analysis_score")
	_variant.Status = field.NewString(tableName, "status")
	_variant.SourceLanguage = field.NewString(tableName, "source_language")
	_variant.SourceRootURI = field.NewString(tableName, "source_root_uri")
	_variant.CreatedBy = field.NewInt64(tableName, "created_by")
	_variant.LastImportedAt = field.NewTime(tableName, "last_imported_at")
	_variant.LastReviewedAt = field.NewTime(tableName, "last_reviewed_at")
	_variant.CreatedAt = field.NewTime(tableName, "created_at")
	_variant.UpdatedAt = field.NewTime(tableName, "updated_at")

	_variant.fillFieldMap()

	return _variant
}

type variant struct {
	variantDo variantDo

	ALL                 field.Asterisk
	ID                  field.Int64
	ProjectID           field.Int64
	Name                field.String
	Description         field.String
	IsMain              field.Bool
	ForkedFromVariantID field.Int64
	AnalysisScore       field.Int32
	Status              field.String
	SourceLanguage      field.String
	SourceRootURI       field.String
	CreatedBy           field.Int64
	LastImportedAt      field.Time
	LastReviewedAt      field.Time
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (v variant) Table(newTableName string) *variant {
	v.variantDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v variant) As(alias string) *variant {
	v.variantDo.DO = *(v.variantDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *variant) updateTableName(table string) *variant {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.ProjectID = field.NewInt64(table, "project_id")
	v.Name = field.NewString(table, "name")
	v.Description = field.NewString(table, "description")
	v.IsMain = field.NewBool(table, "is_main")
	v.ForkedFromVariantID = field.NewInt64(table, "forked_from_variant_id")
	v.AnalysisScore = field.NewInt32(table, "analysis_score")
	v.Status = field.NewString(table, "status")
	v.SourceLanguage = field.NewString(table, "source_language")
	v.SourceRootURI = field.NewString(table, "source_root_uri")
	v.CreatedBy = field.NewInt64(table, "created_by")
	v.LastImportedAt = field.NewTime(table, "last_imported_at")
	v.LastReviewedAt = field.NewTime(table, "last_reviewed_at")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *variant) WithContext(ctx context.Context) IVariantDo { return v.variantDo.WithContext(ctx) }

func (v variant) TableName() string { return v.variantDo.TableName() }

func (v variant) Alias() string { return v.variantDo.Alias() }

func (v variant) Columns(cols ...field.Expr) gen.Columns { return v.variantDo.Columns(cols...) }

func (v *variant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *variant) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 15)
	v.fieldMap["id"] = v.ID
	v.fieldMap["project_id"] = v.ProjectID
	v.fieldMap["name"] = v.Name
	v.fieldMap["description"] = v.Description
	v.fieldMap["is_main"] = v.IsMain
	v.fieldMap["forked_from_variant_id"] = v.ForkedFromVariantID
	v.fieldMap["analysis_score"] = v.AnalysisScore
	v.fieldMap["status"] = v.Status
	v.fieldMap["source_language"] = v.SourceLanguage
	v.fieldMap["source_root_uri"] = v.SourceRootURI
	v.fieldMap["created_by"] = v.CreatedBy
	v.fieldMap["last_imported_at"] = v.LastImportedAt
	v.fieldMap["last_reviewed_at"] = v.LastReviewedAt
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v variant) clone(db *gorm.DB) variant {
	v.variantDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v variant) replaceDB(db *gorm.DB) variant {
	v.variantDo.ReplaceDB(db)
	return v
}

type variantDo struct{ gen.DO }

type IVariantDo interface {
	gen.SubQuery
	Debug() IVariantDo
	WithContext(ctx context.Context) IVariantDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVariantDo
	WriteDB() IVariantDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVariantDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVariantDo
	Not(conds ...gen.Condition) IVariantDo
	Or(conds ...gen.Condition) IVariantDo
	Select(conds ...field.Expr) IVariantDo
	Where(conds ...gen.Condition) IVariantDo
	Order(conds ...field.Expr) IVariantDo
	Distinct(cols ...field.Expr) IVariantDo
	Omit(cols ...field.Expr) IVariantDo
	Join(table schema.Tabler, on ...field.Expr) IVariantDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVariantDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVariantDo
	Group(cols ...field.Expr) IVariantDo
	Having(conds ...gen.Condition) IVariantDo
	Limit(limit int) IVariantDo
	Offset(offset int) IVariantDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVariantDo
	Unscoped() IVariantDo
	Create(values ...*entity.Variant) error
	CreateInBatches(values []*entity.Variant, batchSize int) error
	Save(values ...*entity.Variant) error
	First() (*entity.Variant, error)
	Take() (*entity.Variant, error)
	Last() (*entity.Variant, error)
	Find() ([]*entity.Variant, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Variant, err error)
	FindInBatches(result *[]*entity.Variant, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Variant) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVariantDo
	Assign(attrs ...field.AssignExpr) IVariantDo
	Joins(fields ...field.RelationField) IVariantDo
	Preload(fields ...field.RelationField) IVariantDo
	FirstOrInit() (*entity.Variant, error)
	FirstOrCreate() (*entity.Variant, error)
	FindByPage(offset int, limit int) (result []*entity.Variant, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVariantDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v variantDo) Debug() IVariantDo {
	return v.withDO(v.DO.Debug())
}

func (v variantDo) WithContext(ctx context.Context) IVariantDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v variantDo) ReadDB() IVariantDo {
	return v.Clauses(dbresolver.Read)
}

func (v variantDo) WriteDB() IVariantDo {
	return v.Clauses(dbresolver.Write)
}

func (v variantDo) Session(config *gorm.Session) IVariantDo {
	return v.withDO(v.DO.Session(config))
}

func (v variantDo) Clauses(conds ...clause.Expression) IVariantDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v variantDo) Returning(value interface{}, columns ...string) IVariantDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v variantDo) Not(conds ...gen.Condition) IVariantDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v variantDo) Or(conds ...gen.Condition) IVariantDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v variantDo) Select(conds ...field.Expr) IVariantDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v variantDo) Where(conds ...gen.Condition) IVariantDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v variantDo) Order(conds ...field.Expr) IVariantDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v variantDo) Distinct(cols ...field.Expr) IVariantDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v variantDo) Omit(cols ...field.Expr) IVariantDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v variantDo) Join(table schema.Tabler, on ...field.Expr) IVariantDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v variantDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVariantDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v variantDo) RightJoin(table schema.Tabler, on ...field.Expr) IVariantDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v variantDo) Group(cols ...field.Expr) IVariantDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v variantDo) Having(conds ...gen.Condition) IVariantDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v variantDo) Limit(limit int) IVariantDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v variantDo) Offset(offset int) IVariantDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v variantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVariantDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v variantDo) Unscoped() IVariantDo {
	return v.withDO(v.DO.Unscoped())
}

func (v variantDo) Create(values ...*entity.Variant) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v variantDo) CreateInBatches(values []*entity.Variant, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v variantDo) Save(values ...*entity.Variant) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v variantDo) First() (*entity.Variant, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Variant), nil
	}
}

func (v variantDo) Take() (*entity.Variant, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Variant), nil
	}
}

func (v variantDo) Last() (*entity.Variant, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Variant), nil
	}
}

func (v variantDo) Find() ([]*entity.Variant, error) {
	result, err := v.DO.Find()
	return result.([]*entity.Variant), err
}

func (v variantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Variant, err error) {
	buf := make([]*entity.Variant, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v variantDo) FindInBatches(result *[]*entity.Variant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v variantDo) Attrs(attrs ...field.AssignExpr) IVariantDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v variantDo) Assign(attrs ...field.AssignExpr) IVariantDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v variantDo) Joins(fields ...field.RelationField) IVariantDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v variantDo) Preload(fields ...field.RelationField) IVariantDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v variantDo) FirstOrInit() (*entity.Variant, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Variant), nil
	}
}

func (v variantDo) FirstOrCreate() (*entity.Variant, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Variant), nil
	}
}

func (v variantDo) FindByPage(offset int, limit int) (result []*entity.Variant, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v variantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v variantDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v variantDo) Delete(models ...*entity.Variant) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *variantDo) withDO(do gen.Dao) *variantDo {
	v.DO = *do.(*gen.DO)
	return v
}
