name: Bug Report
description: File a bug report.
title: "[Bug]: "
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        改善内容に関するISSUE記載
  - type: textarea
    id: about-feature
    attributes:
      label: ISSUE概要
      description: バグの概要を書いてください.
      placeholder: 〇〇が発生.
    validations:
      required: true
  - type: textarea
    id: todo-feature
    attributes:
      label: TODOs
      description: TODOリストを書いてください.
      placeholder: 〇〇を実装する.
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: バージョン
      description: どのバージョンで発生しましたか？
      placeholder: version X.X.X
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: どのブラウザ（端末）で発生していますか？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - iOS
        - Android
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: エラーコードやログが分かれば共有してください.
      description: Copy and paste here.
      render: shell
  - type: textarea
    id: other-feature
    attributes:
      label: 備考
      description: その他で記載すること.
      placeholder: 特になし.
    validations:
      required: false
